CREATE TABLE ru (id VARCHAR(64) NOT NULL, value VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO ru ("id", "value") VALUES (E'AU', E'Австралия');
INSERT INTO ru ("id", "value") VALUES (E'AT', E'Австрия');
INSERT INTO ru ("id", "value") VALUES (E'AZ', E'Азербайджан');
INSERT INTO ru ("id", "value") VALUES (E'AX', E'Аландские о-ва');
INSERT INTO ru ("id", "value") VALUES (E'AL', E'Албания');
INSERT INTO ru ("id", "value") VALUES (E'DZ', E'Алжир');
INSERT INTO ru ("id", "value") VALUES (E'AS', E'Американское Самоа');
INSERT INTO ru ("id", "value") VALUES (E'AI', E'Ангилья');
INSERT INTO ru ("id", "value") VALUES (E'AO', E'Ангола');
INSERT INTO ru ("id", "value") VALUES (E'AD', E'Андорра');
INSERT INTO ru ("id", "value") VALUES (E'AQ', E'Антарктида');
INSERT INTO ru ("id", "value") VALUES (E'AG', E'Антигуа и Барбуда');
INSERT INTO ru ("id", "value") VALUES (E'AR', E'Аргентина');
INSERT INTO ru ("id", "value") VALUES (E'AM', E'Армения');
INSERT INTO ru ("id", "value") VALUES (E'AW', E'Аруба');
INSERT INTO ru ("id", "value") VALUES (E'AF', E'Афганистан');
INSERT INTO ru ("id", "value") VALUES (E'BS', E'Багамы');
INSERT INTO ru ("id", "value") VALUES (E'BD', E'Бангладеш');
INSERT INTO ru ("id", "value") VALUES (E'BB', E'Барбадос');
INSERT INTO ru ("id", "value") VALUES (E'BH', E'Бахрейн');
INSERT INTO ru ("id", "value") VALUES (E'BY', E'Беларусь');
INSERT INTO ru ("id", "value") VALUES (E'BZ', E'Белиз');
INSERT INTO ru ("id", "value") VALUES (E'BE', E'Бельгия');
INSERT INTO ru ("id", "value") VALUES (E'BJ', E'Бенин');
INSERT INTO ru ("id", "value") VALUES (E'BM', E'Бермудские о-ва');
INSERT INTO ru ("id", "value") VALUES (E'BG', E'Болгария');
INSERT INTO ru ("id", "value") VALUES (E'BO', E'Боливия');
INSERT INTO ru ("id", "value") VALUES (E'BQ', E'Бонэйр, Синт-Эстатиус и Саба');
INSERT INTO ru ("id", "value") VALUES (E'BA', E'Босния и Герцеговина');
INSERT INTO ru ("id", "value") VALUES (E'BW', E'Ботсвана');
INSERT INTO ru ("id", "value") VALUES (E'BR', E'Бразилия');
INSERT INTO ru ("id", "value") VALUES (E'IO', E'Британская территория в Индийском океане');
INSERT INTO ru ("id", "value") VALUES (E'BN', E'Бруней-Даруссалам');
INSERT INTO ru ("id", "value") VALUES (E'BF', E'Буркина-Фасо');
INSERT INTO ru ("id", "value") VALUES (E'BI', E'Бурунди');
INSERT INTO ru ("id", "value") VALUES (E'BT', E'Бутан');
INSERT INTO ru ("id", "value") VALUES (E'VU', E'Вануату');
INSERT INTO ru ("id", "value") VALUES (E'VA', E'Ватикан');
INSERT INTO ru ("id", "value") VALUES (E'GB', E'Великобритания');
INSERT INTO ru ("id", "value") VALUES (E'HU', E'Венгрия');
INSERT INTO ru ("id", "value") VALUES (E'VE', E'Венесуэла');
INSERT INTO ru ("id", "value") VALUES (E'VG', E'Виргинские о-ва (Великобритания)');
INSERT INTO ru ("id", "value") VALUES (E'VI', E'Виргинские о-ва (США)');
INSERT INTO ru ("id", "value") VALUES (E'UM', E'Внешние малые о-ва (США)');
INSERT INTO ru ("id", "value") VALUES (E'TL', E'Восточный Тимор');
INSERT INTO ru ("id", "value") VALUES (E'VN', E'Вьетнам');
INSERT INTO ru ("id", "value") VALUES (E'GA', E'Габон');
INSERT INTO ru ("id", "value") VALUES (E'HT', E'Гаити');
INSERT INTO ru ("id", "value") VALUES (E'GY', E'Гайана');
INSERT INTO ru ("id", "value") VALUES (E'GM', E'Гамбия');
INSERT INTO ru ("id", "value") VALUES (E'GH', E'Гана');
INSERT INTO ru ("id", "value") VALUES (E'GP', E'Гваделупа');
INSERT INTO ru ("id", "value") VALUES (E'GT', E'Гватемала');
INSERT INTO ru ("id", "value") VALUES (E'GN', E'Гвинея');
INSERT INTO ru ("id", "value") VALUES (E'GW', E'Гвинея-Бисау');
INSERT INTO ru ("id", "value") VALUES (E'DE', E'Германия');
INSERT INTO ru ("id", "value") VALUES (E'GG', E'Гернси');
INSERT INTO ru ("id", "value") VALUES (E'GI', E'Гибралтар');
INSERT INTO ru ("id", "value") VALUES (E'HN', E'Гондурас');
INSERT INTO ru ("id", "value") VALUES (E'HK', E'Гонконг (САР)');
INSERT INTO ru ("id", "value") VALUES (E'GD', E'Гренада');
INSERT INTO ru ("id", "value") VALUES (E'GL', E'Гренландия');
INSERT INTO ru ("id", "value") VALUES (E'GR', E'Греция');
INSERT INTO ru ("id", "value") VALUES (E'GE', E'Грузия');
INSERT INTO ru ("id", "value") VALUES (E'GU', E'Гуам');
INSERT INTO ru ("id", "value") VALUES (E'DK', E'Дания');
INSERT INTO ru ("id", "value") VALUES (E'JE', E'Джерси');
INSERT INTO ru ("id", "value") VALUES (E'DJ', E'Джибути');
INSERT INTO ru ("id", "value") VALUES (E'DG', E'Диего-Гарсия');
INSERT INTO ru ("id", "value") VALUES (E'DM', E'Доминика');
INSERT INTO ru ("id", "value") VALUES (E'DO', E'Доминиканская Республика');
INSERT INTO ru ("id", "value") VALUES (E'EG', E'Египет');
INSERT INTO ru ("id", "value") VALUES (E'ZM', E'Замбия');
INSERT INTO ru ("id", "value") VALUES (E'EH', E'Западная Сахара');
INSERT INTO ru ("id", "value") VALUES (E'ZW', E'Зимбабве');
INSERT INTO ru ("id", "value") VALUES (E'IL', E'Израиль');
INSERT INTO ru ("id", "value") VALUES (E'IN', E'Индия');
INSERT INTO ru ("id", "value") VALUES (E'ID', E'Индонезия');
INSERT INTO ru ("id", "value") VALUES (E'JO', E'Иордания');
INSERT INTO ru ("id", "value") VALUES (E'IQ', E'Ирак');
INSERT INTO ru ("id", "value") VALUES (E'IR', E'Иран');
INSERT INTO ru ("id", "value") VALUES (E'IE', E'Ирландия');
INSERT INTO ru ("id", "value") VALUES (E'IS', E'Исландия');
INSERT INTO ru ("id", "value") VALUES (E'ES', E'Испания');
INSERT INTO ru ("id", "value") VALUES (E'IT', E'Италия');
INSERT INTO ru ("id", "value") VALUES (E'YE', E'Йемен');
INSERT INTO ru ("id", "value") VALUES (E'CV', E'Кабо-Верде');
INSERT INTO ru ("id", "value") VALUES (E'KZ', E'Казахстан');
INSERT INTO ru ("id", "value") VALUES (E'KH', E'Камбоджа');
INSERT INTO ru ("id", "value") VALUES (E'CM', E'Камерун');
INSERT INTO ru ("id", "value") VALUES (E'CA', E'Канада');
INSERT INTO ru ("id", "value") VALUES (E'IC', E'Канарские о-ва');
INSERT INTO ru ("id", "value") VALUES (E'QA', E'Катар');
INSERT INTO ru ("id", "value") VALUES (E'KE', E'Кения');
INSERT INTO ru ("id", "value") VALUES (E'CY', E'Кипр');
INSERT INTO ru ("id", "value") VALUES (E'KG', E'Киргизия');
INSERT INTO ru ("id", "value") VALUES (E'KI', E'Кирибати');
INSERT INTO ru ("id", "value") VALUES (E'CN', E'Китай');
INSERT INTO ru ("id", "value") VALUES (E'KP', E'КНДР');
INSERT INTO ru ("id", "value") VALUES (E'CC', E'Кокосовые о-ва');
INSERT INTO ru ("id", "value") VALUES (E'CO', E'Колумбия');
INSERT INTO ru ("id", "value") VALUES (E'KM', E'Коморы');
INSERT INTO ru ("id", "value") VALUES (E'CG', E'Конго - Браззавиль');
INSERT INTO ru ("id", "value") VALUES (E'CD', E'Конго - Киншаса');
INSERT INTO ru ("id", "value") VALUES (E'XK', E'Косово');
INSERT INTO ru ("id", "value") VALUES (E'CR', E'Коста-Рика');
INSERT INTO ru ("id", "value") VALUES (E'CI', E'Кот-д’Ивуар');
INSERT INTO ru ("id", "value") VALUES (E'CU', E'Куба');
INSERT INTO ru ("id", "value") VALUES (E'KW', E'Кувейт');
INSERT INTO ru ("id", "value") VALUES (E'CW', E'Кюрасао');
INSERT INTO ru ("id", "value") VALUES (E'LA', E'Лаос');
INSERT INTO ru ("id", "value") VALUES (E'LV', E'Латвия');
INSERT INTO ru ("id", "value") VALUES (E'LS', E'Лесото');
INSERT INTO ru ("id", "value") VALUES (E'LR', E'Либерия');
INSERT INTO ru ("id", "value") VALUES (E'LB', E'Ливан');
INSERT INTO ru ("id", "value") VALUES (E'LY', E'Ливия');
INSERT INTO ru ("id", "value") VALUES (E'LT', E'Литва');
INSERT INTO ru ("id", "value") VALUES (E'LI', E'Лихтенштейн');
INSERT INTO ru ("id", "value") VALUES (E'LU', E'Люксембург');
INSERT INTO ru ("id", "value") VALUES (E'MU', E'Маврикий');
INSERT INTO ru ("id", "value") VALUES (E'MR', E'Мавритания');
INSERT INTO ru ("id", "value") VALUES (E'MG', E'Мадагаскар');
INSERT INTO ru ("id", "value") VALUES (E'YT', E'Майотта');
INSERT INTO ru ("id", "value") VALUES (E'MO', E'Макао (САР)');
INSERT INTO ru ("id", "value") VALUES (E'MW', E'Малави');
INSERT INTO ru ("id", "value") VALUES (E'MY', E'Малайзия');
INSERT INTO ru ("id", "value") VALUES (E'ML', E'Мали');
INSERT INTO ru ("id", "value") VALUES (E'MV', E'Мальдивы');
INSERT INTO ru ("id", "value") VALUES (E'MT', E'Мальта');
INSERT INTO ru ("id", "value") VALUES (E'MA', E'Марокко');
INSERT INTO ru ("id", "value") VALUES (E'MQ', E'Мартиника');
INSERT INTO ru ("id", "value") VALUES (E'MH', E'Маршалловы Острова');
INSERT INTO ru ("id", "value") VALUES (E'MX', E'Мексика');
INSERT INTO ru ("id", "value") VALUES (E'MZ', E'Мозамбик');
INSERT INTO ru ("id", "value") VALUES (E'MD', E'Молдова');
INSERT INTO ru ("id", "value") VALUES (E'MC', E'Монако');
INSERT INTO ru ("id", "value") VALUES (E'MN', E'Монголия');
INSERT INTO ru ("id", "value") VALUES (E'MS', E'Монтсеррат');
INSERT INTO ru ("id", "value") VALUES (E'MM', E'Мьянма (Бирма)');
INSERT INTO ru ("id", "value") VALUES (E'NA', E'Намибия');
INSERT INTO ru ("id", "value") VALUES (E'NR', E'Науру');
INSERT INTO ru ("id", "value") VALUES (E'NP', E'Непал');
INSERT INTO ru ("id", "value") VALUES (E'NE', E'Нигер');
INSERT INTO ru ("id", "value") VALUES (E'NG', E'Нигерия');
INSERT INTO ru ("id", "value") VALUES (E'NL', E'Нидерланды');
INSERT INTO ru ("id", "value") VALUES (E'NI', E'Никарагуа');
INSERT INTO ru ("id", "value") VALUES (E'NU', E'Ниуэ');
INSERT INTO ru ("id", "value") VALUES (E'NZ', E'Новая Зеландия');
INSERT INTO ru ("id", "value") VALUES (E'NC', E'Новая Каледония');
INSERT INTO ru ("id", "value") VALUES (E'NO', E'Норвегия');
INSERT INTO ru ("id", "value") VALUES (E'AC', E'о-в Вознесения');
INSERT INTO ru ("id", "value") VALUES (E'IM', E'о-в Мэн');
INSERT INTO ru ("id", "value") VALUES (E'NF', E'о-в Норфолк');
INSERT INTO ru ("id", "value") VALUES (E'CX', E'о-в Рождества');
INSERT INTO ru ("id", "value") VALUES (E'SH', E'о-в Св. Елены');
INSERT INTO ru ("id", "value") VALUES (E'PN', E'о-ва Питкэрн');
INSERT INTO ru ("id", "value") VALUES (E'TC', E'о-ва Тёркс и Кайкос');
INSERT INTO ru ("id", "value") VALUES (E'AE', E'ОАЭ');
INSERT INTO ru ("id", "value") VALUES (E'OM', E'Оман');
INSERT INTO ru ("id", "value") VALUES (E'KY', E'Острова Кайман');
INSERT INTO ru ("id", "value") VALUES (E'CK', E'Острова Кука');
INSERT INTO ru ("id", "value") VALUES (E'PK', E'Пакистан');
INSERT INTO ru ("id", "value") VALUES (E'PW', E'Палау');
INSERT INTO ru ("id", "value") VALUES (E'PS', E'Палестинские территории');
INSERT INTO ru ("id", "value") VALUES (E'PA', E'Панама');
INSERT INTO ru ("id", "value") VALUES (E'PG', E'Папуа — Новая Гвинея');
INSERT INTO ru ("id", "value") VALUES (E'PY', E'Парагвай');
INSERT INTO ru ("id", "value") VALUES (E'PE', E'Перу');
INSERT INTO ru ("id", "value") VALUES (E'PL', E'Польша');
INSERT INTO ru ("id", "value") VALUES (E'PT', E'Португалия');
INSERT INTO ru ("id", "value") VALUES (E'XB', E'псевдо-Bidi');
INSERT INTO ru ("id", "value") VALUES (E'XA', E'псевдоакценты');
INSERT INTO ru ("id", "value") VALUES (E'PR', E'Пуэрто-Рико');
INSERT INTO ru ("id", "value") VALUES (E'KR', E'Республика Корея');
INSERT INTO ru ("id", "value") VALUES (E'RE', E'Реюньон');
INSERT INTO ru ("id", "value") VALUES (E'RU', E'Россия');
INSERT INTO ru ("id", "value") VALUES (E'RW', E'Руанда');
INSERT INTO ru ("id", "value") VALUES (E'RO', E'Румыния');
INSERT INTO ru ("id", "value") VALUES (E'SV', E'Сальвадор');
INSERT INTO ru ("id", "value") VALUES (E'WS', E'Самоа');
INSERT INTO ru ("id", "value") VALUES (E'SM', E'Сан-Марино');
INSERT INTO ru ("id", "value") VALUES (E'ST', E'Сан-Томе и Принсипи');
INSERT INTO ru ("id", "value") VALUES (E'SA', E'Саудовская Аравия');
INSERT INTO ru ("id", "value") VALUES (E'MK', E'Северная Македония');
INSERT INTO ru ("id", "value") VALUES (E'MP', E'Северные Марианские о-ва');
INSERT INTO ru ("id", "value") VALUES (E'SC', E'Сейшельские Острова');
INSERT INTO ru ("id", "value") VALUES (E'BL', E'Сен-Бартелеми');
INSERT INTO ru ("id", "value") VALUES (E'MF', E'Сен-Мартен');
INSERT INTO ru ("id", "value") VALUES (E'PM', E'Сен-Пьер и Микелон');
INSERT INTO ru ("id", "value") VALUES (E'SN', E'Сенегал');
INSERT INTO ru ("id", "value") VALUES (E'VC', E'Сент-Винсент и Гренадины');
INSERT INTO ru ("id", "value") VALUES (E'KN', E'Сент-Китс и Невис');
INSERT INTO ru ("id", "value") VALUES (E'LC', E'Сент-Люсия');
INSERT INTO ru ("id", "value") VALUES (E'RS', E'Сербия');
INSERT INTO ru ("id", "value") VALUES (E'EA', E'Сеута и Мелилья');
INSERT INTO ru ("id", "value") VALUES (E'SG', E'Сингапур');
INSERT INTO ru ("id", "value") VALUES (E'SX', E'Синт-Мартен');
INSERT INTO ru ("id", "value") VALUES (E'SY', E'Сирия');
INSERT INTO ru ("id", "value") VALUES (E'SK', E'Словакия');
INSERT INTO ru ("id", "value") VALUES (E'SI', E'Словения');
INSERT INTO ru ("id", "value") VALUES (E'US', E'Соединенные Штаты');
INSERT INTO ru ("id", "value") VALUES (E'SB', E'Соломоновы Острова');
INSERT INTO ru ("id", "value") VALUES (E'SO', E'Сомали');
INSERT INTO ru ("id", "value") VALUES (E'SD', E'Судан');
INSERT INTO ru ("id", "value") VALUES (E'SR', E'Суринам');
INSERT INTO ru ("id", "value") VALUES (E'SL', E'Сьерра-Леоне');
INSERT INTO ru ("id", "value") VALUES (E'TJ', E'Таджикистан');
INSERT INTO ru ("id", "value") VALUES (E'TH', E'Таиланд');
INSERT INTO ru ("id", "value") VALUES (E'TW', E'Тайвань');
INSERT INTO ru ("id", "value") VALUES (E'TZ', E'Танзания');
INSERT INTO ru ("id", "value") VALUES (E'TG', E'Того');
INSERT INTO ru ("id", "value") VALUES (E'TK', E'Токелау');
INSERT INTO ru ("id", "value") VALUES (E'TO', E'Тонга');
INSERT INTO ru ("id", "value") VALUES (E'TT', E'Тринидад и Тобаго');
INSERT INTO ru ("id", "value") VALUES (E'TA', E'Тристан-да-Кунья');
INSERT INTO ru ("id", "value") VALUES (E'TV', E'Тувалу');
INSERT INTO ru ("id", "value") VALUES (E'TN', E'Тунис');
INSERT INTO ru ("id", "value") VALUES (E'TM', E'Туркменистан');
INSERT INTO ru ("id", "value") VALUES (E'TR', E'Турция');
INSERT INTO ru ("id", "value") VALUES (E'UG', E'Уганда');
INSERT INTO ru ("id", "value") VALUES (E'UZ', E'Узбекистан');
INSERT INTO ru ("id", "value") VALUES (E'UA', E'Украина');
INSERT INTO ru ("id", "value") VALUES (E'WF', E'Уоллис и Футуна');
INSERT INTO ru ("id", "value") VALUES (E'UY', E'Уругвай');
INSERT INTO ru ("id", "value") VALUES (E'FO', E'Фарерские о-ва');
INSERT INTO ru ("id", "value") VALUES (E'FM', E'Федеративные Штаты Микронезии');
INSERT INTO ru ("id", "value") VALUES (E'FJ', E'Фиджи');
INSERT INTO ru ("id", "value") VALUES (E'PH', E'Филиппины');
INSERT INTO ru ("id", "value") VALUES (E'FI', E'Финляндия');
INSERT INTO ru ("id", "value") VALUES (E'FK', E'Фолклендские о-ва');
INSERT INTO ru ("id", "value") VALUES (E'FR', E'Франция');
INSERT INTO ru ("id", "value") VALUES (E'GF', E'Французская Гвиана');
INSERT INTO ru ("id", "value") VALUES (E'PF', E'Французская Полинезия');
INSERT INTO ru ("id", "value") VALUES (E'TF', E'Французские Южные территории');
INSERT INTO ru ("id", "value") VALUES (E'HR', E'Хорватия');
INSERT INTO ru ("id", "value") VALUES (E'CF', E'Центрально-Африканская Республика');
INSERT INTO ru ("id", "value") VALUES (E'TD', E'Чад');
INSERT INTO ru ("id", "value") VALUES (E'ME', E'Черногория');
INSERT INTO ru ("id", "value") VALUES (E'CZ', E'Чехия');
INSERT INTO ru ("id", "value") VALUES (E'CL', E'Чили');
INSERT INTO ru ("id", "value") VALUES (E'CH', E'Швейцария');
INSERT INTO ru ("id", "value") VALUES (E'SE', E'Швеция');
INSERT INTO ru ("id", "value") VALUES (E'SJ', E'Шпицберген и Ян-Майен');
INSERT INTO ru ("id", "value") VALUES (E'LK', E'Шри-Ланка');
INSERT INTO ru ("id", "value") VALUES (E'EC', E'Эквадор');
INSERT INTO ru ("id", "value") VALUES (E'GQ', E'Экваториальная Гвинея');
INSERT INTO ru ("id", "value") VALUES (E'ER', E'Эритрея');
INSERT INTO ru ("id", "value") VALUES (E'SZ', E'Эсватини');
INSERT INTO ru ("id", "value") VALUES (E'EE', E'Эстония');
INSERT INTO ru ("id", "value") VALUES (E'ET', E'Эфиопия');
INSERT INTO ru ("id", "value") VALUES (E'GS', E'Южная Георгия и Южные Сандвичевы о-ва');
INSERT INTO ru ("id", "value") VALUES (E'ZA', E'Южно-Африканская Республика');
INSERT INTO ru ("id", "value") VALUES (E'SS', E'Южный Судан');
INSERT INTO ru ("id", "value") VALUES (E'JM', E'Ямайка');
INSERT INTO ru ("id", "value") VALUES (E'JP', E'Япония');
