CREATE TABLE es (id VARCHAR(64) NOT NULL, value VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO es ("id", "value") VALUES (E'AF', E'Afganistán');
INSERT INTO es ("id", "value") VALUES (E'AL', E'Albania');
INSERT INTO es ("id", "value") VALUES (E'DE', E'Alemania');
INSERT INTO es ("id", "value") VALUES (E'AD', E'Andorra');
INSERT INTO es ("id", "value") VALUES (E'AO', E'Angola');
INSERT INTO es ("id", "value") VALUES (E'AI', E'Anguila');
INSERT INTO es ("id", "value") VALUES (E'AQ', E'Antártida');
INSERT INTO es ("id", "value") VALUES (E'AG', E'Antigua y Barbuda');
INSERT INTO es ("id", "value") VALUES (E'SA', E'Arabia Saudí');
INSERT INTO es ("id", "value") VALUES (E'DZ', E'Argelia');
INSERT INTO es ("id", "value") VALUES (E'AR', E'Argentina');
INSERT INTO es ("id", "value") VALUES (E'AM', E'Armenia');
INSERT INTO es ("id", "value") VALUES (E'AW', E'Aruba');
INSERT INTO es ("id", "value") VALUES (E'AU', E'Australia');
INSERT INTO es ("id", "value") VALUES (E'AT', E'Austria');
INSERT INTO es ("id", "value") VALUES (E'AZ', E'Azerbaiyán');
INSERT INTO es ("id", "value") VALUES (E'BS', E'Bahamas');
INSERT INTO es ("id", "value") VALUES (E'BD', E'Bangladés');
INSERT INTO es ("id", "value") VALUES (E'BB', E'Barbados');
INSERT INTO es ("id", "value") VALUES (E'BH', E'Baréin');
INSERT INTO es ("id", "value") VALUES (E'BE', E'Bélgica');
INSERT INTO es ("id", "value") VALUES (E'BZ', E'Belice');
INSERT INTO es ("id", "value") VALUES (E'BJ', E'Benín');
INSERT INTO es ("id", "value") VALUES (E'BM', E'Bermudas');
INSERT INTO es ("id", "value") VALUES (E'BY', E'Bielorrusia');
INSERT INTO es ("id", "value") VALUES (E'BO', E'Bolivia');
INSERT INTO es ("id", "value") VALUES (E'BA', E'Bosnia y Herzegovina');
INSERT INTO es ("id", "value") VALUES (E'BW', E'Botsuana');
INSERT INTO es ("id", "value") VALUES (E'BR', E'Brasil');
INSERT INTO es ("id", "value") VALUES (E'BN', E'Brunéi');
INSERT INTO es ("id", "value") VALUES (E'BG', E'Bulgaria');
INSERT INTO es ("id", "value") VALUES (E'BF', E'Burkina Faso');
INSERT INTO es ("id", "value") VALUES (E'BI', E'Burundi');
INSERT INTO es ("id", "value") VALUES (E'BT', E'Bután');
INSERT INTO es ("id", "value") VALUES (E'CV', E'Cabo Verde');
INSERT INTO es ("id", "value") VALUES (E'KH', E'Camboya');
INSERT INTO es ("id", "value") VALUES (E'CM', E'Camerún');
INSERT INTO es ("id", "value") VALUES (E'CA', E'Canadá');
INSERT INTO es ("id", "value") VALUES (E'IC', E'Canarias');
INSERT INTO es ("id", "value") VALUES (E'BQ', E'Caribe neerlandés');
INSERT INTO es ("id", "value") VALUES (E'QA', E'Catar');
INSERT INTO es ("id", "value") VALUES (E'EA', E'Ceuta y Melilla');
INSERT INTO es ("id", "value") VALUES (E'TD', E'Chad');
INSERT INTO es ("id", "value") VALUES (E'CZ', E'Chequia');
INSERT INTO es ("id", "value") VALUES (E'CL', E'Chile');
INSERT INTO es ("id", "value") VALUES (E'CN', E'China');
INSERT INTO es ("id", "value") VALUES (E'CY', E'Chipre');
INSERT INTO es ("id", "value") VALUES (E'VA', E'Ciudad del Vaticano');
INSERT INTO es ("id", "value") VALUES (E'CO', E'Colombia');
INSERT INTO es ("id", "value") VALUES (E'KM', E'Comoras');
INSERT INTO es ("id", "value") VALUES (E'CG', E'Congo');
INSERT INTO es ("id", "value") VALUES (E'KP', E'Corea del Norte');
INSERT INTO es ("id", "value") VALUES (E'KR', E'Corea del Sur');
INSERT INTO es ("id", "value") VALUES (E'CR', E'Costa Rica');
INSERT INTO es ("id", "value") VALUES (E'CI', E'Côte d’Ivoire');
INSERT INTO es ("id", "value") VALUES (E'HR', E'Croacia');
INSERT INTO es ("id", "value") VALUES (E'CU', E'Cuba');
INSERT INTO es ("id", "value") VALUES (E'CW', E'Curazao');
INSERT INTO es ("id", "value") VALUES (E'DG', E'Diego García');
INSERT INTO es ("id", "value") VALUES (E'DK', E'Dinamarca');
INSERT INTO es ("id", "value") VALUES (E'DM', E'Dominica');
INSERT INTO es ("id", "value") VALUES (E'EC', E'Ecuador');
INSERT INTO es ("id", "value") VALUES (E'EG', E'Egipto');
INSERT INTO es ("id", "value") VALUES (E'SV', E'El Salvador');
INSERT INTO es ("id", "value") VALUES (E'AE', E'Emiratos Árabes Unidos');
INSERT INTO es ("id", "value") VALUES (E'ER', E'Eritrea');
INSERT INTO es ("id", "value") VALUES (E'SK', E'Eslovaquia');
INSERT INTO es ("id", "value") VALUES (E'SI', E'Eslovenia');
INSERT INTO es ("id", "value") VALUES (E'ES', E'España');
INSERT INTO es ("id", "value") VALUES (E'US', E'Estados Unidos');
INSERT INTO es ("id", "value") VALUES (E'EE', E'Estonia');
INSERT INTO es ("id", "value") VALUES (E'SZ', E'Esuatini');
INSERT INTO es ("id", "value") VALUES (E'ET', E'Etiopía');
INSERT INTO es ("id", "value") VALUES (E'PH', E'Filipinas');
INSERT INTO es ("id", "value") VALUES (E'FI', E'Finlandia');
INSERT INTO es ("id", "value") VALUES (E'FJ', E'Fiyi');
INSERT INTO es ("id", "value") VALUES (E'FR', E'Francia');
INSERT INTO es ("id", "value") VALUES (E'GA', E'Gabón');
INSERT INTO es ("id", "value") VALUES (E'GM', E'Gambia');
INSERT INTO es ("id", "value") VALUES (E'GE', E'Georgia');
INSERT INTO es ("id", "value") VALUES (E'GH', E'Ghana');
INSERT INTO es ("id", "value") VALUES (E'GI', E'Gibraltar');
INSERT INTO es ("id", "value") VALUES (E'GD', E'Granada');
INSERT INTO es ("id", "value") VALUES (E'GR', E'Grecia');
INSERT INTO es ("id", "value") VALUES (E'GL', E'Groenlandia');
INSERT INTO es ("id", "value") VALUES (E'GP', E'Guadalupe');
INSERT INTO es ("id", "value") VALUES (E'GU', E'Guam');
INSERT INTO es ("id", "value") VALUES (E'GT', E'Guatemala');
INSERT INTO es ("id", "value") VALUES (E'GF', E'Guayana Francesa');
INSERT INTO es ("id", "value") VALUES (E'GG', E'Guernsey');
INSERT INTO es ("id", "value") VALUES (E'GN', E'Guinea');
INSERT INTO es ("id", "value") VALUES (E'GQ', E'Guinea Ecuatorial');
INSERT INTO es ("id", "value") VALUES (E'GW', E'Guinea-Bisáu');
INSERT INTO es ("id", "value") VALUES (E'GY', E'Guyana');
INSERT INTO es ("id", "value") VALUES (E'HT', E'Haití');
INSERT INTO es ("id", "value") VALUES (E'HN', E'Honduras');
INSERT INTO es ("id", "value") VALUES (E'HU', E'Hungría');
INSERT INTO es ("id", "value") VALUES (E'IN', E'India');
INSERT INTO es ("id", "value") VALUES (E'ID', E'Indonesia');
INSERT INTO es ("id", "value") VALUES (E'IQ', E'Irak');
INSERT INTO es ("id", "value") VALUES (E'IR', E'Irán');
INSERT INTO es ("id", "value") VALUES (E'IE', E'Irlanda');
INSERT INTO es ("id", "value") VALUES (E'AC', E'Isla de la Ascensión');
INSERT INTO es ("id", "value") VALUES (E'IM', E'Isla de Man');
INSERT INTO es ("id", "value") VALUES (E'CX', E'Isla de Navidad');
INSERT INTO es ("id", "value") VALUES (E'NF', E'Isla Norfolk');
INSERT INTO es ("id", "value") VALUES (E'IS', E'Islandia');
INSERT INTO es ("id", "value") VALUES (E'AX', E'Islas Åland');
INSERT INTO es ("id", "value") VALUES (E'KY', E'Islas Caimán');
INSERT INTO es ("id", "value") VALUES (E'CC', E'Islas Cocos');
INSERT INTO es ("id", "value") VALUES (E'CK', E'Islas Cook');
INSERT INTO es ("id", "value") VALUES (E'FO', E'Islas Feroe');
INSERT INTO es ("id", "value") VALUES (E'GS', E'Islas Georgia del Sur y Sandwich del Sur');
INSERT INTO es ("id", "value") VALUES (E'FK', E'Islas Malvinas');
INSERT INTO es ("id", "value") VALUES (E'MP', E'Islas Marianas del Norte');
INSERT INTO es ("id", "value") VALUES (E'MH', E'Islas Marshall');
INSERT INTO es ("id", "value") VALUES (E'UM', E'Islas menores alejadas de EE. UU.');
INSERT INTO es ("id", "value") VALUES (E'PN', E'Islas Pitcairn');
INSERT INTO es ("id", "value") VALUES (E'SB', E'Islas Salomón');
INSERT INTO es ("id", "value") VALUES (E'TC', E'Islas Turcas y Caicos');
INSERT INTO es ("id", "value") VALUES (E'VG', E'Islas Vírgenes Británicas');
INSERT INTO es ("id", "value") VALUES (E'VI', E'Islas Vírgenes de EE. UU.');
INSERT INTO es ("id", "value") VALUES (E'IL', E'Israel');
INSERT INTO es ("id", "value") VALUES (E'IT', E'Italia');
INSERT INTO es ("id", "value") VALUES (E'JM', E'Jamaica');
INSERT INTO es ("id", "value") VALUES (E'JP', E'Japón');
INSERT INTO es ("id", "value") VALUES (E'JE', E'Jersey');
INSERT INTO es ("id", "value") VALUES (E'JO', E'Jordania');
INSERT INTO es ("id", "value") VALUES (E'KZ', E'Kazajistán');
INSERT INTO es ("id", "value") VALUES (E'KE', E'Kenia');
INSERT INTO es ("id", "value") VALUES (E'KG', E'Kirguistán');
INSERT INTO es ("id", "value") VALUES (E'KI', E'Kiribati');
INSERT INTO es ("id", "value") VALUES (E'XK', E'Kosovo');
INSERT INTO es ("id", "value") VALUES (E'KW', E'Kuwait');
INSERT INTO es ("id", "value") VALUES (E'LA', E'Laos');
INSERT INTO es ("id", "value") VALUES (E'LS', E'Lesoto');
INSERT INTO es ("id", "value") VALUES (E'LV', E'Letonia');
INSERT INTO es ("id", "value") VALUES (E'LB', E'Líbano');
INSERT INTO es ("id", "value") VALUES (E'LR', E'Liberia');
INSERT INTO es ("id", "value") VALUES (E'LY', E'Libia');
INSERT INTO es ("id", "value") VALUES (E'LI', E'Liechtenstein');
INSERT INTO es ("id", "value") VALUES (E'LT', E'Lituania');
INSERT INTO es ("id", "value") VALUES (E'LU', E'Luxemburgo');
INSERT INTO es ("id", "value") VALUES (E'MK', E'Macedonia');
INSERT INTO es ("id", "value") VALUES (E'MG', E'Madagascar');
INSERT INTO es ("id", "value") VALUES (E'MY', E'Malasia');
INSERT INTO es ("id", "value") VALUES (E'MW', E'Malaui');
INSERT INTO es ("id", "value") VALUES (E'MV', E'Maldivas');
INSERT INTO es ("id", "value") VALUES (E'ML', E'Mali');
INSERT INTO es ("id", "value") VALUES (E'MT', E'Malta');
INSERT INTO es ("id", "value") VALUES (E'MA', E'Marruecos');
INSERT INTO es ("id", "value") VALUES (E'MQ', E'Martinica');
INSERT INTO es ("id", "value") VALUES (E'MU', E'Mauricio');
INSERT INTO es ("id", "value") VALUES (E'MR', E'Mauritania');
INSERT INTO es ("id", "value") VALUES (E'YT', E'Mayotte');
INSERT INTO es ("id", "value") VALUES (E'MX', E'México');
INSERT INTO es ("id", "value") VALUES (E'FM', E'Micronesia');
INSERT INTO es ("id", "value") VALUES (E'MD', E'Moldavia');
INSERT INTO es ("id", "value") VALUES (E'MC', E'Mónaco');
INSERT INTO es ("id", "value") VALUES (E'MN', E'Mongolia');
INSERT INTO es ("id", "value") VALUES (E'ME', E'Montenegro');
INSERT INTO es ("id", "value") VALUES (E'MS', E'Montserrat');
INSERT INTO es ("id", "value") VALUES (E'MZ', E'Mozambique');
INSERT INTO es ("id", "value") VALUES (E'MM', E'Myanmar (Birmania)');
INSERT INTO es ("id", "value") VALUES (E'NA', E'Namibia');
INSERT INTO es ("id", "value") VALUES (E'NR', E'Nauru');
INSERT INTO es ("id", "value") VALUES (E'NP', E'Nepal');
INSERT INTO es ("id", "value") VALUES (E'NI', E'Nicaragua');
INSERT INTO es ("id", "value") VALUES (E'NE', E'Níger');
INSERT INTO es ("id", "value") VALUES (E'NG', E'Nigeria');
INSERT INTO es ("id", "value") VALUES (E'NU', E'Niue');
INSERT INTO es ("id", "value") VALUES (E'NO', E'Noruega');
INSERT INTO es ("id", "value") VALUES (E'NC', E'Nueva Caledonia');
INSERT INTO es ("id", "value") VALUES (E'NZ', E'Nueva Zelanda');
INSERT INTO es ("id", "value") VALUES (E'OM', E'Omán');
INSERT INTO es ("id", "value") VALUES (E'NL', E'Países Bajos');
INSERT INTO es ("id", "value") VALUES (E'PK', E'Pakistán');
INSERT INTO es ("id", "value") VALUES (E'PW', E'Palaos');
INSERT INTO es ("id", "value") VALUES (E'PA', E'Panamá');
INSERT INTO es ("id", "value") VALUES (E'PG', E'Papúa Nueva Guinea');
INSERT INTO es ("id", "value") VALUES (E'PY', E'Paraguay');
INSERT INTO es ("id", "value") VALUES (E'PE', E'Perú');
INSERT INTO es ("id", "value") VALUES (E'PF', E'Polinesia Francesa');
INSERT INTO es ("id", "value") VALUES (E'PL', E'Polonia');
INSERT INTO es ("id", "value") VALUES (E'PT', E'Portugal');
INSERT INTO es ("id", "value") VALUES (E'XA', E'Pseudo-Accents');
INSERT INTO es ("id", "value") VALUES (E'XB', E'Pseudo-Bidi');
INSERT INTO es ("id", "value") VALUES (E'PR', E'Puerto Rico');
INSERT INTO es ("id", "value") VALUES (E'HK', E'RAE de Hong Kong (China)');
INSERT INTO es ("id", "value") VALUES (E'MO', E'RAE de Macao (China)');
INSERT INTO es ("id", "value") VALUES (E'GB', E'Reino Unido');
INSERT INTO es ("id", "value") VALUES (E'CF', E'República Centroafricana');
INSERT INTO es ("id", "value") VALUES (E'CD', E'República Democrática del Congo');
INSERT INTO es ("id", "value") VALUES (E'DO', E'República Dominicana');
INSERT INTO es ("id", "value") VALUES (E'RE', E'Reunión');
INSERT INTO es ("id", "value") VALUES (E'RW', E'Ruanda');
INSERT INTO es ("id", "value") VALUES (E'RO', E'Rumanía');
INSERT INTO es ("id", "value") VALUES (E'RU', E'Rusia');
INSERT INTO es ("id", "value") VALUES (E'EH', E'Sáhara Occidental');
INSERT INTO es ("id", "value") VALUES (E'WS', E'Samoa');
INSERT INTO es ("id", "value") VALUES (E'AS', E'Samoa Americana');
INSERT INTO es ("id", "value") VALUES (E'BL', E'San Bartolomé');
INSERT INTO es ("id", "value") VALUES (E'KN', E'San Cristóbal y Nieves');
INSERT INTO es ("id", "value") VALUES (E'SM', E'San Marino');
INSERT INTO es ("id", "value") VALUES (E'MF', E'San Martín');
INSERT INTO es ("id", "value") VALUES (E'PM', E'San Pedro y Miquelón');
INSERT INTO es ("id", "value") VALUES (E'VC', E'San Vicente y las Granadinas');
INSERT INTO es ("id", "value") VALUES (E'SH', E'Santa Elena');
INSERT INTO es ("id", "value") VALUES (E'LC', E'Santa Lucía');
INSERT INTO es ("id", "value") VALUES (E'ST', E'Santo Tomé y Príncipe');
INSERT INTO es ("id", "value") VALUES (E'SN', E'Senegal');
INSERT INTO es ("id", "value") VALUES (E'RS', E'Serbia');
INSERT INTO es ("id", "value") VALUES (E'SC', E'Seychelles');
INSERT INTO es ("id", "value") VALUES (E'SL', E'Sierra Leona');
INSERT INTO es ("id", "value") VALUES (E'SG', E'Singapur');
INSERT INTO es ("id", "value") VALUES (E'SX', E'Sint Maarten');
INSERT INTO es ("id", "value") VALUES (E'SY', E'Siria');
INSERT INTO es ("id", "value") VALUES (E'SO', E'Somalia');
INSERT INTO es ("id", "value") VALUES (E'LK', E'Sri Lanka');
INSERT INTO es ("id", "value") VALUES (E'ZA', E'Sudáfrica');
INSERT INTO es ("id", "value") VALUES (E'SD', E'Sudán');
INSERT INTO es ("id", "value") VALUES (E'SS', E'Sudán del Sur');
INSERT INTO es ("id", "value") VALUES (E'SE', E'Suecia');
INSERT INTO es ("id", "value") VALUES (E'CH', E'Suiza');
INSERT INTO es ("id", "value") VALUES (E'SR', E'Surinam');
INSERT INTO es ("id", "value") VALUES (E'SJ', E'Svalbard y Jan Mayen');
INSERT INTO es ("id", "value") VALUES (E'TH', E'Tailandia');
INSERT INTO es ("id", "value") VALUES (E'TW', E'Taiwán');
INSERT INTO es ("id", "value") VALUES (E'TZ', E'Tanzania');
INSERT INTO es ("id", "value") VALUES (E'TJ', E'Tayikistán');
INSERT INTO es ("id", "value") VALUES (E'IO', E'Territorio Británico del Océano Índico');
INSERT INTO es ("id", "value") VALUES (E'TF', E'Territorios Australes Franceses');
INSERT INTO es ("id", "value") VALUES (E'PS', E'Territorios Palestinos');
INSERT INTO es ("id", "value") VALUES (E'TL', E'Timor-Leste');
INSERT INTO es ("id", "value") VALUES (E'TG', E'Togo');
INSERT INTO es ("id", "value") VALUES (E'TK', E'Tokelau');
INSERT INTO es ("id", "value") VALUES (E'TO', E'Tonga');
INSERT INTO es ("id", "value") VALUES (E'TT', E'Trinidad y Tobago');
INSERT INTO es ("id", "value") VALUES (E'TA', E'Tristán de Acuña');
INSERT INTO es ("id", "value") VALUES (E'TN', E'Túnez');
INSERT INTO es ("id", "value") VALUES (E'TM', E'Turkmenistán');
INSERT INTO es ("id", "value") VALUES (E'TR', E'Turquía');
INSERT INTO es ("id", "value") VALUES (E'TV', E'Tuvalu');
INSERT INTO es ("id", "value") VALUES (E'UA', E'Ucrania');
INSERT INTO es ("id", "value") VALUES (E'UG', E'Uganda');
INSERT INTO es ("id", "value") VALUES (E'UY', E'Uruguay');
INSERT INTO es ("id", "value") VALUES (E'UZ', E'Uzbekistán');
INSERT INTO es ("id", "value") VALUES (E'VU', E'Vanuatu');
INSERT INTO es ("id", "value") VALUES (E'VE', E'Venezuela');
INSERT INTO es ("id", "value") VALUES (E'VN', E'Vietnam');
INSERT INTO es ("id", "value") VALUES (E'WF', E'Wallis y Futuna');
INSERT INTO es ("id", "value") VALUES (E'YE', E'Yemen');
INSERT INTO es ("id", "value") VALUES (E'DJ', E'Yibuti');
INSERT INTO es ("id", "value") VALUES (E'ZM', E'Zambia');
INSERT INTO es ("id", "value") VALUES (E'ZW', E'Zimbabue');
