CREATE TABLE lv (id VARCHAR(64) NOT NULL, value VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO lv ("id", "value") VALUES (E'AF', E'Afganistāna');
INSERT INTO lv ("id", "value") VALUES (E'AL', E'Albānija');
INSERT INTO lv ("id", "value") VALUES (E'DZ', E'Alžīrija');
INSERT INTO lv ("id", "value") VALUES (E'US', E'Amerikas Savienotās Valstis');
INSERT INTO lv ("id", "value") VALUES (E'AD', E'Andora');
INSERT INTO lv ("id", "value") VALUES (E'AI', E'Angilja');
INSERT INTO lv ("id", "value") VALUES (E'AO', E'Angola');
INSERT INTO lv ("id", "value") VALUES (E'AQ', E'Antarktika');
INSERT INTO lv ("id", "value") VALUES (E'AG', E'Antigva un Barbuda');
INSERT INTO lv ("id", "value") VALUES (E'GB', E'Apvienotā Karaliste');
INSERT INTO lv ("id", "value") VALUES (E'AE', E'Apvienotie Arābu Emirāti');
INSERT INTO lv ("id", "value") VALUES (E'AR', E'Argentīna');
INSERT INTO lv ("id", "value") VALUES (E'AM', E'Armēnija');
INSERT INTO lv ("id", "value") VALUES (E'AW', E'Aruba');
INSERT INTO lv ("id", "value") VALUES (E'UM', E'ASV Mazās Aizjūras salas');
INSERT INTO lv ("id", "value") VALUES (E'AS', E'ASV Samoa');
INSERT INTO lv ("id", "value") VALUES (E'VI', E'ASV Virdžīnas');
INSERT INTO lv ("id", "value") VALUES (E'AU', E'Austrālija');
INSERT INTO lv ("id", "value") VALUES (E'AT', E'Austrija');
INSERT INTO lv ("id", "value") VALUES (E'TL', E'Austrumtimora');
INSERT INTO lv ("id", "value") VALUES (E'AZ', E'Azerbaidžāna');
INSERT INTO lv ("id", "value") VALUES (E'BS', E'Bahamu salas');
INSERT INTO lv ("id", "value") VALUES (E'BH', E'Bahreina');
INSERT INTO lv ("id", "value") VALUES (E'BY', E'Baltkrievija');
INSERT INTO lv ("id", "value") VALUES (E'BD', E'Bangladeša');
INSERT INTO lv ("id", "value") VALUES (E'BB', E'Barbadosa');
INSERT INTO lv ("id", "value") VALUES (E'BZ', E'Beliza');
INSERT INTO lv ("id", "value") VALUES (E'BE', E'Beļģija');
INSERT INTO lv ("id", "value") VALUES (E'BJ', E'Benina');
INSERT INTO lv ("id", "value") VALUES (E'BM', E'Bermudu salas');
INSERT INTO lv ("id", "value") VALUES (E'BO', E'Bolīvija');
INSERT INTO lv ("id", "value") VALUES (E'BA', E'Bosnija un Hercegovina');
INSERT INTO lv ("id", "value") VALUES (E'BW', E'Botsvāna');
INSERT INTO lv ("id", "value") VALUES (E'BR', E'Brazīlija');
INSERT INTO lv ("id", "value") VALUES (E'VG', E'Britu Virdžīnas');
INSERT INTO lv ("id", "value") VALUES (E'BN', E'Bruneja');
INSERT INTO lv ("id", "value") VALUES (E'BG', E'Bulgārija');
INSERT INTO lv ("id", "value") VALUES (E'BF', E'Burkinafaso');
INSERT INTO lv ("id", "value") VALUES (E'BI', E'Burundija');
INSERT INTO lv ("id", "value") VALUES (E'BT', E'Butāna');
INSERT INTO lv ("id", "value") VALUES (E'CF', E'Centrālāfrikas Republika');
INSERT INTO lv ("id", "value") VALUES (E'TD', E'Čada');
INSERT INTO lv ("id", "value") VALUES (E'CZ', E'Čehija');
INSERT INTO lv ("id", "value") VALUES (E'CL', E'Čīle');
INSERT INTO lv ("id", "value") VALUES (E'DK', E'Dānija');
INSERT INTO lv ("id", "value") VALUES (E'AC', E'Debesbraukšanas sala');
INSERT INTO lv ("id", "value") VALUES (E'ZA', E'Dienvidāfrikas Republika');
INSERT INTO lv ("id", "value") VALUES (E'GS', E'Dienviddžordžija un Dienvidsendviču salas');
INSERT INTO lv ("id", "value") VALUES (E'KR', E'Dienvidkoreja');
INSERT INTO lv ("id", "value") VALUES (E'SS', E'Dienvidsudāna');
INSERT INTO lv ("id", "value") VALUES (E'DG', E'Djego Garsijas atols');
INSERT INTO lv ("id", "value") VALUES (E'DM', E'Dominika');
INSERT INTO lv ("id", "value") VALUES (E'DO', E'Dominikāna');
INSERT INTO lv ("id", "value") VALUES (E'JE', E'Džērsija');
INSERT INTO lv ("id", "value") VALUES (E'DJ', E'Džibutija');
INSERT INTO lv ("id", "value") VALUES (E'EG', E'Ēģipte');
INSERT INTO lv ("id", "value") VALUES (E'EC', E'Ekvadora');
INSERT INTO lv ("id", "value") VALUES (E'GQ', E'Ekvatoriālā Gvineja');
INSERT INTO lv ("id", "value") VALUES (E'ER', E'Eritreja');
INSERT INTO lv ("id", "value") VALUES (E'ET', E'Etiopija');
INSERT INTO lv ("id", "value") VALUES (E'FO', E'Fēru salas');
INSERT INTO lv ("id", "value") VALUES (E'FJ', E'Fidži');
INSERT INTO lv ("id", "value") VALUES (E'PH', E'Filipīnas');
INSERT INTO lv ("id", "value") VALUES (E'FK', E'Folklenda salas');
INSERT INTO lv ("id", "value") VALUES (E'FR', E'Francija');
INSERT INTO lv ("id", "value") VALUES (E'TF', E'Francijas Dienvidjūru teritorija');
INSERT INTO lv ("id", "value") VALUES (E'GF', E'Francijas Gviāna');
INSERT INTO lv ("id", "value") VALUES (E'PF', E'Francijas Polinēzija');
INSERT INTO lv ("id", "value") VALUES (E'GA', E'Gabona');
INSERT INTO lv ("id", "value") VALUES (E'GY', E'Gajāna');
INSERT INTO lv ("id", "value") VALUES (E'GM', E'Gambija');
INSERT INTO lv ("id", "value") VALUES (E'GH', E'Gana');
INSERT INTO lv ("id", "value") VALUES (E'GG', E'Gērnsija');
INSERT INTO lv ("id", "value") VALUES (E'GI', E'Gibraltārs');
INSERT INTO lv ("id", "value") VALUES (E'GD', E'Grenāda');
INSERT INTO lv ("id", "value") VALUES (E'GL', E'Grenlande');
INSERT INTO lv ("id", "value") VALUES (E'GR', E'Grieķija');
INSERT INTO lv ("id", "value") VALUES (E'GE', E'Gruzija');
INSERT INTO lv ("id", "value") VALUES (E'GU', E'Guama');
INSERT INTO lv ("id", "value") VALUES (E'GP', E'Gvadelupa');
INSERT INTO lv ("id", "value") VALUES (E'GT', E'Gvatemala');
INSERT INTO lv ("id", "value") VALUES (E'GN', E'Gvineja');
INSERT INTO lv ("id", "value") VALUES (E'GW', E'Gvineja-Bisava');
INSERT INTO lv ("id", "value") VALUES (E'HT', E'Haiti');
INSERT INTO lv ("id", "value") VALUES (E'HN', E'Hondurasa');
INSERT INTO lv ("id", "value") VALUES (E'HR', E'Horvātija');
INSERT INTO lv ("id", "value") VALUES (E'EE', E'Igaunija');
INSERT INTO lv ("id", "value") VALUES (E'IN', E'Indija');
INSERT INTO lv ("id", "value") VALUES (E'IO', E'Indijas okeāna Britu teritorija');
INSERT INTO lv ("id", "value") VALUES (E'ID', E'Indonēzija');
INSERT INTO lv ("id", "value") VALUES (E'IQ', E'Irāka');
INSERT INTO lv ("id", "value") VALUES (E'IR', E'Irāna');
INSERT INTO lv ("id", "value") VALUES (E'IE', E'Īrija');
INSERT INTO lv ("id", "value") VALUES (E'IS', E'Islande');
INSERT INTO lv ("id", "value") VALUES (E'IT', E'Itālija');
INSERT INTO lv ("id", "value") VALUES (E'IL', E'Izraēla');
INSERT INTO lv ("id", "value") VALUES (E'JM', E'Jamaika');
INSERT INTO lv ("id", "value") VALUES (E'JP', E'Japāna');
INSERT INTO lv ("id", "value") VALUES (E'NC', E'Jaunkaledonija');
INSERT INTO lv ("id", "value") VALUES (E'NZ', E'Jaunzēlande');
INSERT INTO lv ("id", "value") VALUES (E'YE', E'Jemena');
INSERT INTO lv ("id", "value") VALUES (E'JO', E'Jordānija');
INSERT INTO lv ("id", "value") VALUES (E'CV', E'Kaboverde');
INSERT INTO lv ("id", "value") VALUES (E'KY', E'Kaimanu salas');
INSERT INTO lv ("id", "value") VALUES (E'KH', E'Kambodža');
INSERT INTO lv ("id", "value") VALUES (E'CM', E'Kamerūna');
INSERT INTO lv ("id", "value") VALUES (E'CA', E'Kanāda');
INSERT INTO lv ("id", "value") VALUES (E'IC', E'Kanāriju salas');
INSERT INTO lv ("id", "value") VALUES (E'QA', E'Katara');
INSERT INTO lv ("id", "value") VALUES (E'KZ', E'Kazahstāna');
INSERT INTO lv ("id", "value") VALUES (E'KE', E'Kenija');
INSERT INTO lv ("id", "value") VALUES (E'CY', E'Kipra');
INSERT INTO lv ("id", "value") VALUES (E'CW', E'Kirasao');
INSERT INTO lv ("id", "value") VALUES (E'KG', E'Kirgizstāna');
INSERT INTO lv ("id", "value") VALUES (E'KI', E'Kiribati');
INSERT INTO lv ("id", "value") VALUES (E'CC', E'Kokosu (Kīlinga) salas');
INSERT INTO lv ("id", "value") VALUES (E'CO', E'Kolumbija');
INSERT INTO lv ("id", "value") VALUES (E'KM', E'Komoru salas');
INSERT INTO lv ("id", "value") VALUES (E'CG', E'Kongo (Brazavila)');
INSERT INTO lv ("id", "value") VALUES (E'CD', E'Kongo (Kinšasa)');
INSERT INTO lv ("id", "value") VALUES (E'XK', E'Kosova');
INSERT INTO lv ("id", "value") VALUES (E'CR', E'Kostarika');
INSERT INTO lv ("id", "value") VALUES (E'CI', E'Kotdivuāra');
INSERT INTO lv ("id", "value") VALUES (E'RU', E'Krievija');
INSERT INTO lv ("id", "value") VALUES (E'CU', E'Kuba');
INSERT INTO lv ("id", "value") VALUES (E'CK', E'Kuka salas');
INSERT INTO lv ("id", "value") VALUES (E'KW', E'Kuveita');
INSERT INTO lv ("id", "value") VALUES (E'CN', E'Ķīna');
INSERT INTO lv ("id", "value") VALUES (E'HK', E'Ķīnas īpašās pārvaldes apgabals Honkonga');
INSERT INTO lv ("id", "value") VALUES (E'MO', E'Ķīnas īpašās pārvaldes apgabals Makao');
INSERT INTO lv ("id", "value") VALUES (E'LA', E'Laosa');
INSERT INTO lv ("id", "value") VALUES (E'LV', E'Latvija');
INSERT INTO lv ("id", "value") VALUES (E'LS', E'Lesoto');
INSERT INTO lv ("id", "value") VALUES (E'LB', E'Libāna');
INSERT INTO lv ("id", "value") VALUES (E'LR', E'Libērija');
INSERT INTO lv ("id", "value") VALUES (E'LY', E'Lībija');
INSERT INTO lv ("id", "value") VALUES (E'LT', E'Lietuva');
INSERT INTO lv ("id", "value") VALUES (E'LI', E'Lihtenšteina');
INSERT INTO lv ("id", "value") VALUES (E'LU', E'Luksemburga');
INSERT INTO lv ("id", "value") VALUES (E'MG', E'Madagaskara');
INSERT INTO lv ("id", "value") VALUES (E'YT', E'Majota');
INSERT INTO lv ("id", "value") VALUES (E'MY', E'Malaizija');
INSERT INTO lv ("id", "value") VALUES (E'MW', E'Malāvija');
INSERT INTO lv ("id", "value") VALUES (E'MV', E'Maldīvija');
INSERT INTO lv ("id", "value") VALUES (E'ML', E'Mali');
INSERT INTO lv ("id", "value") VALUES (E'MT', E'Malta');
INSERT INTO lv ("id", "value") VALUES (E'MA', E'Maroka');
INSERT INTO lv ("id", "value") VALUES (E'MH', E'Māršala salas');
INSERT INTO lv ("id", "value") VALUES (E'MQ', E'Martinika');
INSERT INTO lv ("id", "value") VALUES (E'MU', E'Maurīcija');
INSERT INTO lv ("id", "value") VALUES (E'MR', E'Mauritānija');
INSERT INTO lv ("id", "value") VALUES (E'MX', E'Meksika');
INSERT INTO lv ("id", "value") VALUES (E'ME', E'Melnkalne');
INSERT INTO lv ("id", "value") VALUES (E'IM', E'Mena');
INSERT INTO lv ("id", "value") VALUES (E'FM', E'Mikronēzija');
INSERT INTO lv ("id", "value") VALUES (E'MM', E'Mjanma (Birma)');
INSERT INTO lv ("id", "value") VALUES (E'MD', E'Moldova');
INSERT INTO lv ("id", "value") VALUES (E'MC', E'Monako');
INSERT INTO lv ("id", "value") VALUES (E'MN', E'Mongolija');
INSERT INTO lv ("id", "value") VALUES (E'MS', E'Montserrata');
INSERT INTO lv ("id", "value") VALUES (E'MZ', E'Mozambika');
INSERT INTO lv ("id", "value") VALUES (E'NA', E'Namībija');
INSERT INTO lv ("id", "value") VALUES (E'NR', E'Nauru');
INSERT INTO lv ("id", "value") VALUES (E'NP', E'Nepāla');
INSERT INTO lv ("id", "value") VALUES (E'NL', E'Nīderlande');
INSERT INTO lv ("id", "value") VALUES (E'BQ', E'Nīderlandes Karību salas');
INSERT INTO lv ("id", "value") VALUES (E'NE', E'Nigēra');
INSERT INTO lv ("id", "value") VALUES (E'NG', E'Nigērija');
INSERT INTO lv ("id", "value") VALUES (E'NI', E'Nikaragva');
INSERT INTO lv ("id", "value") VALUES (E'NU', E'Niue');
INSERT INTO lv ("id", "value") VALUES (E'NF', E'Norfolkas sala');
INSERT INTO lv ("id", "value") VALUES (E'NO', E'Norvēģija');
INSERT INTO lv ("id", "value") VALUES (E'AX', E'Olandes salas');
INSERT INTO lv ("id", "value") VALUES (E'OM', E'Omāna');
INSERT INTO lv ("id", "value") VALUES (E'PK', E'Pakistāna');
INSERT INTO lv ("id", "value") VALUES (E'PW', E'Palau');
INSERT INTO lv ("id", "value") VALUES (E'PS', E'Palestīna');
INSERT INTO lv ("id", "value") VALUES (E'PA', E'Panama');
INSERT INTO lv ("id", "value") VALUES (E'PG', E'Papua-Jaungvineja');
INSERT INTO lv ("id", "value") VALUES (E'PY', E'Paragvaja');
INSERT INTO lv ("id", "value") VALUES (E'PE', E'Peru');
INSERT INTO lv ("id", "value") VALUES (E'PN', E'Pitkērnas salas');
INSERT INTO lv ("id", "value") VALUES (E'PL', E'Polija');
INSERT INTO lv ("id", "value") VALUES (E'PT', E'Portugāle');
INSERT INTO lv ("id", "value") VALUES (E'XB', E'pseido-Bidi');
INSERT INTO lv ("id", "value") VALUES (E'XA', E'pseidoakcenti');
INSERT INTO lv ("id", "value") VALUES (E'PR', E'Puertoriko');
INSERT INTO lv ("id", "value") VALUES (E'RE', E'Reinjona');
INSERT INTO lv ("id", "value") VALUES (E'EH', E'Rietumsahāra');
INSERT INTO lv ("id", "value") VALUES (E'RW', E'Ruanda');
INSERT INTO lv ("id", "value") VALUES (E'RO', E'Rumānija');
INSERT INTO lv ("id", "value") VALUES (E'SV', E'Salvadora');
INSERT INTO lv ("id", "value") VALUES (E'WS', E'Samoa');
INSERT INTO lv ("id", "value") VALUES (E'SM', E'Sanmarīno');
INSERT INTO lv ("id", "value") VALUES (E'ST', E'Santome un Prinsipi');
INSERT INTO lv ("id", "value") VALUES (E'SA', E'Saūda Arābija');
INSERT INTO lv ("id", "value") VALUES (E'SC', E'Seišelu salas');
INSERT INTO lv ("id", "value") VALUES (E'BL', E'Senbartelmī');
INSERT INTO lv ("id", "value") VALUES (E'SN', E'Senegāla');
INSERT INTO lv ("id", "value") VALUES (E'MF', E'Senmartēna');
INSERT INTO lv ("id", "value") VALUES (E'PM', E'Senpjēra un Mikelona');
INSERT INTO lv ("id", "value") VALUES (E'KN', E'Sentkitsa un Nevisa');
INSERT INTO lv ("id", "value") VALUES (E'LC', E'Sentlūsija');
INSERT INTO lv ("id", "value") VALUES (E'VC', E'Sentvinsenta un Grenadīnas');
INSERT INTO lv ("id", "value") VALUES (E'RS', E'Serbija');
INSERT INTO lv ("id", "value") VALUES (E'EA', E'Seūta un Melilja');
INSERT INTO lv ("id", "value") VALUES (E'SG', E'Singapūra');
INSERT INTO lv ("id", "value") VALUES (E'SX', E'Sintmārtena');
INSERT INTO lv ("id", "value") VALUES (E'SY', E'Sīrija');
INSERT INTO lv ("id", "value") VALUES (E'SL', E'Sjerraleone');
INSERT INTO lv ("id", "value") VALUES (E'SK', E'Slovākija');
INSERT INTO lv ("id", "value") VALUES (E'SI', E'Slovēnija');
INSERT INTO lv ("id", "value") VALUES (E'SO', E'Somālija');
INSERT INTO lv ("id", "value") VALUES (E'FI', E'Somija');
INSERT INTO lv ("id", "value") VALUES (E'ES', E'Spānija');
INSERT INTO lv ("id", "value") VALUES (E'SD', E'Sudāna');
INSERT INTO lv ("id", "value") VALUES (E'SR', E'Surinama');
INSERT INTO lv ("id", "value") VALUES (E'SH', E'Sv.Helēnas sala');
INSERT INTO lv ("id", "value") VALUES (E'SJ', E'Svalbāra un Jana Majena sala');
INSERT INTO lv ("id", "value") VALUES (E'SZ', E'Svazilenda');
INSERT INTO lv ("id", "value") VALUES (E'LK', E'Šrilanka');
INSERT INTO lv ("id", "value") VALUES (E'CH', E'Šveice');
INSERT INTO lv ("id", "value") VALUES (E'TJ', E'Tadžikistāna');
INSERT INTO lv ("id", "value") VALUES (E'TW', E'Taivāna');
INSERT INTO lv ("id", "value") VALUES (E'TH', E'Taizeme');
INSERT INTO lv ("id", "value") VALUES (E'TZ', E'Tanzānija');
INSERT INTO lv ("id", "value") VALUES (E'TC', E'Tērksas un Kaikosas salas');
INSERT INTO lv ("id", "value") VALUES (E'TG', E'Togo');
INSERT INTO lv ("id", "value") VALUES (E'TK', E'Tokelau');
INSERT INTO lv ("id", "value") VALUES (E'TO', E'Tonga');
INSERT INTO lv ("id", "value") VALUES (E'TT', E'Trinidāda un Tobāgo');
INSERT INTO lv ("id", "value") VALUES (E'TA', E'Tristana da Kuņas salas');
INSERT INTO lv ("id", "value") VALUES (E'TN', E'Tunisija');
INSERT INTO lv ("id", "value") VALUES (E'TR', E'Turcija');
INSERT INTO lv ("id", "value") VALUES (E'TM', E'Turkmenistāna');
INSERT INTO lv ("id", "value") VALUES (E'TV', E'Tuvalu');
INSERT INTO lv ("id", "value") VALUES (E'UG', E'Uganda');
INSERT INTO lv ("id", "value") VALUES (E'UA', E'Ukraina');
INSERT INTO lv ("id", "value") VALUES (E'HU', E'Ungārija');
INSERT INTO lv ("id", "value") VALUES (E'UY', E'Urugvaja');
INSERT INTO lv ("id", "value") VALUES (E'UZ', E'Uzbekistāna');
INSERT INTO lv ("id", "value") VALUES (E'DE', E'Vācija');
INSERT INTO lv ("id", "value") VALUES (E'VU', E'Vanuatu');
INSERT INTO lv ("id", "value") VALUES (E'VA', E'Vatikāns');
INSERT INTO lv ("id", "value") VALUES (E'VE', E'Venecuēla');
INSERT INTO lv ("id", "value") VALUES (E'VN', E'Vjetnama');
INSERT INTO lv ("id", "value") VALUES (E'WF', E'Volisa un Futunas salas');
INSERT INTO lv ("id", "value") VALUES (E'SB', E'Zālamana salas');
INSERT INTO lv ("id", "value") VALUES (E'ZM', E'Zambija');
INSERT INTO lv ("id", "value") VALUES (E'KP', E'Ziemeļkoreja');
INSERT INTO lv ("id", "value") VALUES (E'MK', E'Ziemeļmaķedonija');
INSERT INTO lv ("id", "value") VALUES (E'MP', E'Ziemeļu Marianas salas');
INSERT INTO lv ("id", "value") VALUES (E'CX', E'Ziemsvētku sala');
INSERT INTO lv ("id", "value") VALUES (E'ZW', E'Zimbabve');
INSERT INTO lv ("id", "value") VALUES (E'SE', E'Zviedrija');
