CREATE TABLE de (id VARCHAR(64) NOT NULL, value VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO de ("id", "value") VALUES (E'AF', E'Afghanistan');
INSERT INTO de ("id", "value") VALUES (E'EG', E'Ägypten');
INSERT INTO de ("id", "value") VALUES (E'AX', E'Ålandinseln');
INSERT INTO de ("id", "value") VALUES (E'AL', E'Albanien');
INSERT INTO de ("id", "value") VALUES (E'DZ', E'Algerien');
INSERT INTO de ("id", "value") VALUES (E'AS', E'Amerikanisch-Samoa');
INSERT INTO de ("id", "value") VALUES (E'VI', E'Amerikanische Jungferninseln');
INSERT INTO de ("id", "value") VALUES (E'UM', E'Amerikanische Überseeinseln');
INSERT INTO de ("id", "value") VALUES (E'AD', E'Andorra');
INSERT INTO de ("id", "value") VALUES (E'AO', E'Angola');
INSERT INTO de ("id", "value") VALUES (E'AI', E'Anguilla');
INSERT INTO de ("id", "value") VALUES (E'AQ', E'Antarktis');
INSERT INTO de ("id", "value") VALUES (E'AG', E'Antigua und Barbuda');
INSERT INTO de ("id", "value") VALUES (E'GQ', E'Äquatorialguinea');
INSERT INTO de ("id", "value") VALUES (E'AR', E'Argentinien');
INSERT INTO de ("id", "value") VALUES (E'AM', E'Armenien');
INSERT INTO de ("id", "value") VALUES (E'AW', E'Aruba');
INSERT INTO de ("id", "value") VALUES (E'AC', E'Ascension');
INSERT INTO de ("id", "value") VALUES (E'AZ', E'Aserbaidschan');
INSERT INTO de ("id", "value") VALUES (E'ET', E'Äthiopien');
INSERT INTO de ("id", "value") VALUES (E'AU', E'Australien');
INSERT INTO de ("id", "value") VALUES (E'BS', E'Bahamas');
INSERT INTO de ("id", "value") VALUES (E'BH', E'Bahrain');
INSERT INTO de ("id", "value") VALUES (E'BD', E'Bangladesch');
INSERT INTO de ("id", "value") VALUES (E'BB', E'Barbados');
INSERT INTO de ("id", "value") VALUES (E'BY', E'Belarus');
INSERT INTO de ("id", "value") VALUES (E'BE', E'Belgien');
INSERT INTO de ("id", "value") VALUES (E'BZ', E'Belize');
INSERT INTO de ("id", "value") VALUES (E'BJ', E'Benin');
INSERT INTO de ("id", "value") VALUES (E'BM', E'Bermuda');
INSERT INTO de ("id", "value") VALUES (E'BT', E'Bhutan');
INSERT INTO de ("id", "value") VALUES (E'BO', E'Bolivien');
INSERT INTO de ("id", "value") VALUES (E'BQ', E'Bonaire, Sint Eustatius und Saba');
INSERT INTO de ("id", "value") VALUES (E'BA', E'Bosnien und Herzegowina');
INSERT INTO de ("id", "value") VALUES (E'BW', E'Botsuana');
INSERT INTO de ("id", "value") VALUES (E'BR', E'Brasilien');
INSERT INTO de ("id", "value") VALUES (E'VG', E'Britische Jungferninseln');
INSERT INTO de ("id", "value") VALUES (E'IO', E'Britisches Territorium im Indischen Ozean');
INSERT INTO de ("id", "value") VALUES (E'BN', E'Brunei Darussalam');
INSERT INTO de ("id", "value") VALUES (E'BG', E'Bulgarien');
INSERT INTO de ("id", "value") VALUES (E'BF', E'Burkina Faso');
INSERT INTO de ("id", "value") VALUES (E'BI', E'Burundi');
INSERT INTO de ("id", "value") VALUES (E'CV', E'Cabo Verde');
INSERT INTO de ("id", "value") VALUES (E'EA', E'Ceuta und Melilla');
INSERT INTO de ("id", "value") VALUES (E'CL', E'Chile');
INSERT INTO de ("id", "value") VALUES (E'CN', E'China');
INSERT INTO de ("id", "value") VALUES (E'CK', E'Cookinseln');
INSERT INTO de ("id", "value") VALUES (E'CR', E'Costa Rica');
INSERT INTO de ("id", "value") VALUES (E'CI', E'Côte d’Ivoire');
INSERT INTO de ("id", "value") VALUES (E'CW', E'Curaçao');
INSERT INTO de ("id", "value") VALUES (E'DK', E'Dänemark');
INSERT INTO de ("id", "value") VALUES (E'DE', E'Deutschland');
INSERT INTO de ("id", "value") VALUES (E'DG', E'Diego Garcia');
INSERT INTO de ("id", "value") VALUES (E'DM', E'Dominica');
INSERT INTO de ("id", "value") VALUES (E'DO', E'Dominikanische Republik');
INSERT INTO de ("id", "value") VALUES (E'DJ', E'Dschibuti');
INSERT INTO de ("id", "value") VALUES (E'EC', E'Ecuador');
INSERT INTO de ("id", "value") VALUES (E'SV', E'El Salvador');
INSERT INTO de ("id", "value") VALUES (E'ER', E'Eritrea');
INSERT INTO de ("id", "value") VALUES (E'EE', E'Estland');
INSERT INTO de ("id", "value") VALUES (E'FK', E'Falklandinseln');
INSERT INTO de ("id", "value") VALUES (E'FO', E'Färöer');
INSERT INTO de ("id", "value") VALUES (E'FJ', E'Fidschi');
INSERT INTO de ("id", "value") VALUES (E'FI', E'Finnland');
INSERT INTO de ("id", "value") VALUES (E'FR', E'Frankreich');
INSERT INTO de ("id", "value") VALUES (E'GF', E'Französisch-Guayana');
INSERT INTO de ("id", "value") VALUES (E'PF', E'Französisch-Polynesien');
INSERT INTO de ("id", "value") VALUES (E'TF', E'Französische Süd- und Antarktisgebiete');
INSERT INTO de ("id", "value") VALUES (E'GA', E'Gabun');
INSERT INTO de ("id", "value") VALUES (E'GM', E'Gambia');
INSERT INTO de ("id", "value") VALUES (E'GE', E'Georgien');
INSERT INTO de ("id", "value") VALUES (E'GH', E'Ghana');
INSERT INTO de ("id", "value") VALUES (E'GI', E'Gibraltar');
INSERT INTO de ("id", "value") VALUES (E'GD', E'Grenada');
INSERT INTO de ("id", "value") VALUES (E'GR', E'Griechenland');
INSERT INTO de ("id", "value") VALUES (E'GL', E'Grönland');
INSERT INTO de ("id", "value") VALUES (E'GP', E'Guadeloupe');
INSERT INTO de ("id", "value") VALUES (E'GU', E'Guam');
INSERT INTO de ("id", "value") VALUES (E'GT', E'Guatemala');
INSERT INTO de ("id", "value") VALUES (E'GG', E'Guernsey');
INSERT INTO de ("id", "value") VALUES (E'GN', E'Guinea');
INSERT INTO de ("id", "value") VALUES (E'GW', E'Guinea-Bissau');
INSERT INTO de ("id", "value") VALUES (E'GY', E'Guyana');
INSERT INTO de ("id", "value") VALUES (E'HT', E'Haiti');
INSERT INTO de ("id", "value") VALUES (E'HN', E'Honduras');
INSERT INTO de ("id", "value") VALUES (E'IN', E'Indien');
INSERT INTO de ("id", "value") VALUES (E'ID', E'Indonesien');
INSERT INTO de ("id", "value") VALUES (E'IQ', E'Irak');
INSERT INTO de ("id", "value") VALUES (E'IR', E'Iran');
INSERT INTO de ("id", "value") VALUES (E'IE', E'Irland');
INSERT INTO de ("id", "value") VALUES (E'IS', E'Island');
INSERT INTO de ("id", "value") VALUES (E'IM', E'Isle of Man');
INSERT INTO de ("id", "value") VALUES (E'IL', E'Israel');
INSERT INTO de ("id", "value") VALUES (E'IT', E'Italien');
INSERT INTO de ("id", "value") VALUES (E'JM', E'Jamaika');
INSERT INTO de ("id", "value") VALUES (E'JP', E'Japan');
INSERT INTO de ("id", "value") VALUES (E'YE', E'Jemen');
INSERT INTO de ("id", "value") VALUES (E'JE', E'Jersey');
INSERT INTO de ("id", "value") VALUES (E'JO', E'Jordanien');
INSERT INTO de ("id", "value") VALUES (E'KY', E'Kaimaninseln');
INSERT INTO de ("id", "value") VALUES (E'KH', E'Kambodscha');
INSERT INTO de ("id", "value") VALUES (E'CM', E'Kamerun');
INSERT INTO de ("id", "value") VALUES (E'CA', E'Kanada');
INSERT INTO de ("id", "value") VALUES (E'IC', E'Kanarische Inseln');
INSERT INTO de ("id", "value") VALUES (E'KZ', E'Kasachstan');
INSERT INTO de ("id", "value") VALUES (E'QA', E'Katar');
INSERT INTO de ("id", "value") VALUES (E'KE', E'Kenia');
INSERT INTO de ("id", "value") VALUES (E'KG', E'Kirgisistan');
INSERT INTO de ("id", "value") VALUES (E'KI', E'Kiribati');
INSERT INTO de ("id", "value") VALUES (E'CC', E'Kokosinseln');
INSERT INTO de ("id", "value") VALUES (E'CO', E'Kolumbien');
INSERT INTO de ("id", "value") VALUES (E'KM', E'Komoren');
INSERT INTO de ("id", "value") VALUES (E'CG', E'Kongo-Brazzaville');
INSERT INTO de ("id", "value") VALUES (E'CD', E'Kongo-Kinshasa');
INSERT INTO de ("id", "value") VALUES (E'XK', E'Kosovo');
INSERT INTO de ("id", "value") VALUES (E'HR', E'Kroatien');
INSERT INTO de ("id", "value") VALUES (E'CU', E'Kuba');
INSERT INTO de ("id", "value") VALUES (E'KW', E'Kuwait');
INSERT INTO de ("id", "value") VALUES (E'LA', E'Laos');
INSERT INTO de ("id", "value") VALUES (E'LS', E'Lesotho');
INSERT INTO de ("id", "value") VALUES (E'LV', E'Lettland');
INSERT INTO de ("id", "value") VALUES (E'LB', E'Libanon');
INSERT INTO de ("id", "value") VALUES (E'LR', E'Liberia');
INSERT INTO de ("id", "value") VALUES (E'LY', E'Libyen');
INSERT INTO de ("id", "value") VALUES (E'LI', E'Liechtenstein');
INSERT INTO de ("id", "value") VALUES (E'LT', E'Litauen');
INSERT INTO de ("id", "value") VALUES (E'LU', E'Luxemburg');
INSERT INTO de ("id", "value") VALUES (E'MG', E'Madagaskar');
INSERT INTO de ("id", "value") VALUES (E'MW', E'Malawi');
INSERT INTO de ("id", "value") VALUES (E'MY', E'Malaysia');
INSERT INTO de ("id", "value") VALUES (E'MV', E'Malediven');
INSERT INTO de ("id", "value") VALUES (E'ML', E'Mali');
INSERT INTO de ("id", "value") VALUES (E'MT', E'Malta');
INSERT INTO de ("id", "value") VALUES (E'MA', E'Marokko');
INSERT INTO de ("id", "value") VALUES (E'MH', E'Marshallinseln');
INSERT INTO de ("id", "value") VALUES (E'MQ', E'Martinique');
INSERT INTO de ("id", "value") VALUES (E'MR', E'Mauretanien');
INSERT INTO de ("id", "value") VALUES (E'MU', E'Mauritius');
INSERT INTO de ("id", "value") VALUES (E'YT', E'Mayotte');
INSERT INTO de ("id", "value") VALUES (E'MX', E'Mexiko');
INSERT INTO de ("id", "value") VALUES (E'FM', E'Mikronesien');
INSERT INTO de ("id", "value") VALUES (E'MC', E'Monaco');
INSERT INTO de ("id", "value") VALUES (E'MN', E'Mongolei');
INSERT INTO de ("id", "value") VALUES (E'ME', E'Montenegro');
INSERT INTO de ("id", "value") VALUES (E'MS', E'Montserrat');
INSERT INTO de ("id", "value") VALUES (E'MZ', E'Mosambik');
INSERT INTO de ("id", "value") VALUES (E'MM', E'Myanmar');
INSERT INTO de ("id", "value") VALUES (E'NA', E'Namibia');
INSERT INTO de ("id", "value") VALUES (E'NR', E'Nauru');
INSERT INTO de ("id", "value") VALUES (E'NP', E'Nepal');
INSERT INTO de ("id", "value") VALUES (E'NC', E'Neukaledonien');
INSERT INTO de ("id", "value") VALUES (E'NZ', E'Neuseeland');
INSERT INTO de ("id", "value") VALUES (E'NI', E'Nicaragua');
INSERT INTO de ("id", "value") VALUES (E'NL', E'Niederlande');
INSERT INTO de ("id", "value") VALUES (E'NE', E'Niger');
INSERT INTO de ("id", "value") VALUES (E'NG', E'Nigeria');
INSERT INTO de ("id", "value") VALUES (E'NU', E'Niue');
INSERT INTO de ("id", "value") VALUES (E'KP', E'Nordkorea');
INSERT INTO de ("id", "value") VALUES (E'MP', E'Nördliche Marianen');
INSERT INTO de ("id", "value") VALUES (E'MK', E'Nordmazedonien');
INSERT INTO de ("id", "value") VALUES (E'NF', E'Norfolkinsel');
INSERT INTO de ("id", "value") VALUES (E'NO', E'Norwegen');
INSERT INTO de ("id", "value") VALUES (E'OM', E'Oman');
INSERT INTO de ("id", "value") VALUES (E'AT', E'Österreich');
INSERT INTO de ("id", "value") VALUES (E'PK', E'Pakistan');
INSERT INTO de ("id", "value") VALUES (E'PS', E'Palästinensische Autonomiegebiete');
INSERT INTO de ("id", "value") VALUES (E'PW', E'Palau');
INSERT INTO de ("id", "value") VALUES (E'PA', E'Panama');
INSERT INTO de ("id", "value") VALUES (E'PG', E'Papua-Neuguinea');
INSERT INTO de ("id", "value") VALUES (E'PY', E'Paraguay');
INSERT INTO de ("id", "value") VALUES (E'PE', E'Peru');
INSERT INTO de ("id", "value") VALUES (E'PH', E'Philippinen');
INSERT INTO de ("id", "value") VALUES (E'PN', E'Pitcairninseln');
INSERT INTO de ("id", "value") VALUES (E'PL', E'Polen');
INSERT INTO de ("id", "value") VALUES (E'PT', E'Portugal');
INSERT INTO de ("id", "value") VALUES (E'XA', E'Pseudo-Accents');
INSERT INTO de ("id", "value") VALUES (E'XB', E'Pseudo-Bidi');
INSERT INTO de ("id", "value") VALUES (E'PR', E'Puerto Rico');
INSERT INTO de ("id", "value") VALUES (E'MD', E'Republik Moldau');
INSERT INTO de ("id", "value") VALUES (E'RE', E'Réunion');
INSERT INTO de ("id", "value") VALUES (E'RW', E'Ruanda');
INSERT INTO de ("id", "value") VALUES (E'RO', E'Rumänien');
INSERT INTO de ("id", "value") VALUES (E'RU', E'Russland');
INSERT INTO de ("id", "value") VALUES (E'SB', E'Salomonen');
INSERT INTO de ("id", "value") VALUES (E'ZM', E'Sambia');
INSERT INTO de ("id", "value") VALUES (E'WS', E'Samoa');
INSERT INTO de ("id", "value") VALUES (E'SM', E'San Marino');
INSERT INTO de ("id", "value") VALUES (E'ST', E'São Tomé und Príncipe');
INSERT INTO de ("id", "value") VALUES (E'SA', E'Saudi-Arabien');
INSERT INTO de ("id", "value") VALUES (E'SE', E'Schweden');
INSERT INTO de ("id", "value") VALUES (E'CH', E'Schweiz');
INSERT INTO de ("id", "value") VALUES (E'SN', E'Senegal');
INSERT INTO de ("id", "value") VALUES (E'RS', E'Serbien');
INSERT INTO de ("id", "value") VALUES (E'SC', E'Seychellen');
INSERT INTO de ("id", "value") VALUES (E'SL', E'Sierra Leone');
INSERT INTO de ("id", "value") VALUES (E'ZW', E'Simbabwe');
INSERT INTO de ("id", "value") VALUES (E'SG', E'Singapur');
INSERT INTO de ("id", "value") VALUES (E'SX', E'Sint Maarten');
INSERT INTO de ("id", "value") VALUES (E'SK', E'Slowakei');
INSERT INTO de ("id", "value") VALUES (E'SI', E'Slowenien');
INSERT INTO de ("id", "value") VALUES (E'SO', E'Somalia');
INSERT INTO de ("id", "value") VALUES (E'HK', E'Sonderverwaltungsregion Hongkong');
INSERT INTO de ("id", "value") VALUES (E'MO', E'Sonderverwaltungsregion Macau');
INSERT INTO de ("id", "value") VALUES (E'ES', E'Spanien');
INSERT INTO de ("id", "value") VALUES (E'SJ', E'Spitzbergen und Jan Mayen');
INSERT INTO de ("id", "value") VALUES (E'LK', E'Sri Lanka');
INSERT INTO de ("id", "value") VALUES (E'BL', E'St. Barthélemy');
INSERT INTO de ("id", "value") VALUES (E'SH', E'St. Helena');
INSERT INTO de ("id", "value") VALUES (E'KN', E'St. Kitts und Nevis');
INSERT INTO de ("id", "value") VALUES (E'LC', E'St. Lucia');
INSERT INTO de ("id", "value") VALUES (E'MF', E'St. Martin');
INSERT INTO de ("id", "value") VALUES (E'PM', E'St. Pierre und Miquelon');
INSERT INTO de ("id", "value") VALUES (E'VC', E'St. Vincent und die Grenadinen');
INSERT INTO de ("id", "value") VALUES (E'ZA', E'Südafrika');
INSERT INTO de ("id", "value") VALUES (E'SD', E'Sudan');
INSERT INTO de ("id", "value") VALUES (E'GS', E'Südgeorgien und die Südlichen Sandwichinseln');
INSERT INTO de ("id", "value") VALUES (E'KR', E'Südkorea');
INSERT INTO de ("id", "value") VALUES (E'SS', E'Südsudan');
INSERT INTO de ("id", "value") VALUES (E'SR', E'Suriname');
INSERT INTO de ("id", "value") VALUES (E'SZ', E'Swasiland');
INSERT INTO de ("id", "value") VALUES (E'SY', E'Syrien');
INSERT INTO de ("id", "value") VALUES (E'TJ', E'Tadschikistan');
INSERT INTO de ("id", "value") VALUES (E'TW', E'Taiwan');
INSERT INTO de ("id", "value") VALUES (E'TZ', E'Tansania');
INSERT INTO de ("id", "value") VALUES (E'TH', E'Thailand');
INSERT INTO de ("id", "value") VALUES (E'TL', E'Timor-Leste');
INSERT INTO de ("id", "value") VALUES (E'TG', E'Togo');
INSERT INTO de ("id", "value") VALUES (E'TK', E'Tokelau');
INSERT INTO de ("id", "value") VALUES (E'TO', E'Tonga');
INSERT INTO de ("id", "value") VALUES (E'TT', E'Trinidad und Tobago');
INSERT INTO de ("id", "value") VALUES (E'TA', E'Tristan da Cunha');
INSERT INTO de ("id", "value") VALUES (E'TD', E'Tschad');
INSERT INTO de ("id", "value") VALUES (E'CZ', E'Tschechien');
INSERT INTO de ("id", "value") VALUES (E'TN', E'Tunesien');
INSERT INTO de ("id", "value") VALUES (E'TR', E'Türkei');
INSERT INTO de ("id", "value") VALUES (E'TM', E'Turkmenistan');
INSERT INTO de ("id", "value") VALUES (E'TC', E'Turks- und Caicosinseln');
INSERT INTO de ("id", "value") VALUES (E'TV', E'Tuvalu');
INSERT INTO de ("id", "value") VALUES (E'UG', E'Uganda');
INSERT INTO de ("id", "value") VALUES (E'UA', E'Ukraine');
INSERT INTO de ("id", "value") VALUES (E'HU', E'Ungarn');
INSERT INTO de ("id", "value") VALUES (E'UY', E'Uruguay');
INSERT INTO de ("id", "value") VALUES (E'UZ', E'Usbekistan');
INSERT INTO de ("id", "value") VALUES (E'VU', E'Vanuatu');
INSERT INTO de ("id", "value") VALUES (E'VA', E'Vatikanstadt');
INSERT INTO de ("id", "value") VALUES (E'VE', E'Venezuela');
INSERT INTO de ("id", "value") VALUES (E'AE', E'Vereinigte Arabische Emirate');
INSERT INTO de ("id", "value") VALUES (E'US', E'Vereinigte Staaten');
INSERT INTO de ("id", "value") VALUES (E'GB', E'Vereinigtes Königreich');
INSERT INTO de ("id", "value") VALUES (E'VN', E'Vietnam');
INSERT INTO de ("id", "value") VALUES (E'WF', E'Wallis und Futuna');
INSERT INTO de ("id", "value") VALUES (E'CX', E'Weihnachtsinsel');
INSERT INTO de ("id", "value") VALUES (E'EH', E'Westsahara');
INSERT INTO de ("id", "value") VALUES (E'CF', E'Zentralafrikanische Republik');
INSERT INTO de ("id", "value") VALUES (E'CY', E'Zypern');
