CREATE TABLE it (id VARCHAR(64) NOT NULL, value VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO it ("id", "value") VALUES (E'AF', E'Afghanistan');
INSERT INTO it ("id", "value") VALUES (E'AL', E'Albania');
INSERT INTO it ("id", "value") VALUES (E'DZ', E'Algeria');
INSERT INTO it ("id", "value") VALUES (E'UM', E'Altre isole americane del Pacifico');
INSERT INTO it ("id", "value") VALUES (E'AD', E'Andorra');
INSERT INTO it ("id", "value") VALUES (E'AO', E'Angola');
INSERT INTO it ("id", "value") VALUES (E'AI', E'Anguilla');
INSERT INTO it ("id", "value") VALUES (E'AQ', E'Antartide');
INSERT INTO it ("id", "value") VALUES (E'AG', E'Antigua e Barbuda');
INSERT INTO it ("id", "value") VALUES (E'SA', E'Arabia Saudita');
INSERT INTO it ("id", "value") VALUES (E'AR', E'Argentina');
INSERT INTO it ("id", "value") VALUES (E'AM', E'Armenia');
INSERT INTO it ("id", "value") VALUES (E'AW', E'Aruba');
INSERT INTO it ("id", "value") VALUES (E'AU', E'Australia');
INSERT INTO it ("id", "value") VALUES (E'AT', E'Austria');
INSERT INTO it ("id", "value") VALUES (E'AZ', E'Azerbaigian');
INSERT INTO it ("id", "value") VALUES (E'BS', E'Bahamas');
INSERT INTO it ("id", "value") VALUES (E'BH', E'Bahrein');
INSERT INTO it ("id", "value") VALUES (E'BD', E'Bangladesh');
INSERT INTO it ("id", "value") VALUES (E'BB', E'Barbados');
INSERT INTO it ("id", "value") VALUES (E'BE', E'Belgio');
INSERT INTO it ("id", "value") VALUES (E'BZ', E'Belize');
INSERT INTO it ("id", "value") VALUES (E'BJ', E'Benin');
INSERT INTO it ("id", "value") VALUES (E'BM', E'Bermuda');
INSERT INTO it ("id", "value") VALUES (E'BT', E'Bhutan');
INSERT INTO it ("id", "value") VALUES (E'BY', E'Bielorussia');
INSERT INTO it ("id", "value") VALUES (E'BO', E'Bolivia');
INSERT INTO it ("id", "value") VALUES (E'BA', E'Bosnia ed Erzegovina');
INSERT INTO it ("id", "value") VALUES (E'BW', E'Botswana');
INSERT INTO it ("id", "value") VALUES (E'BR', E'Brasile');
INSERT INTO it ("id", "value") VALUES (E'BN', E'Brunei');
INSERT INTO it ("id", "value") VALUES (E'BG', E'Bulgaria');
INSERT INTO it ("id", "value") VALUES (E'BF', E'Burkina Faso');
INSERT INTO it ("id", "value") VALUES (E'BI', E'Burundi');
INSERT INTO it ("id", "value") VALUES (E'KH', E'Cambogia');
INSERT INTO it ("id", "value") VALUES (E'CM', E'Camerun');
INSERT INTO it ("id", "value") VALUES (E'CA', E'Canada');
INSERT INTO it ("id", "value") VALUES (E'CV', E'Capo Verde');
INSERT INTO it ("id", "value") VALUES (E'BQ', E'Caraibi olandesi');
INSERT INTO it ("id", "value") VALUES (E'CZ', E'Cechia');
INSERT INTO it ("id", "value") VALUES (E'EA', E'Ceuta e Melilla');
INSERT INTO it ("id", "value") VALUES (E'TD', E'Ciad');
INSERT INTO it ("id", "value") VALUES (E'CL', E'Cile');
INSERT INTO it ("id", "value") VALUES (E'CN', E'Cina');
INSERT INTO it ("id", "value") VALUES (E'CY', E'Cipro');
INSERT INTO it ("id", "value") VALUES (E'VA', E'Città del Vaticano');
INSERT INTO it ("id", "value") VALUES (E'CO', E'Colombia');
INSERT INTO it ("id", "value") VALUES (E'KM', E'Comore');
INSERT INTO it ("id", "value") VALUES (E'CD', E'Congo - Kinshasa');
INSERT INTO it ("id", "value") VALUES (E'CG', E'Congo-Brazzaville');
INSERT INTO it ("id", "value") VALUES (E'KP', E'Corea del Nord');
INSERT INTO it ("id", "value") VALUES (E'KR', E'Corea del Sud');
INSERT INTO it ("id", "value") VALUES (E'CI', E'Costa d’Avorio');
INSERT INTO it ("id", "value") VALUES (E'CR', E'Costa Rica');
INSERT INTO it ("id", "value") VALUES (E'HR', E'Croazia');
INSERT INTO it ("id", "value") VALUES (E'CU', E'Cuba');
INSERT INTO it ("id", "value") VALUES (E'CW', E'Curaçao');
INSERT INTO it ("id", "value") VALUES (E'DK', E'Danimarca');
INSERT INTO it ("id", "value") VALUES (E'DG', E'Diego Garcia');
INSERT INTO it ("id", "value") VALUES (E'DM', E'Dominica');
INSERT INTO it ("id", "value") VALUES (E'EC', E'Ecuador');
INSERT INTO it ("id", "value") VALUES (E'EG', E'Egitto');
INSERT INTO it ("id", "value") VALUES (E'SV', E'El Salvador');
INSERT INTO it ("id", "value") VALUES (E'AE', E'Emirati Arabi Uniti');
INSERT INTO it ("id", "value") VALUES (E'ER', E'Eritrea');
INSERT INTO it ("id", "value") VALUES (E'EE', E'Estonia');
INSERT INTO it ("id", "value") VALUES (E'ET', E'Etiopia');
INSERT INTO it ("id", "value") VALUES (E'FJ', E'Figi');
INSERT INTO it ("id", "value") VALUES (E'PH', E'Filippine');
INSERT INTO it ("id", "value") VALUES (E'FI', E'Finlandia');
INSERT INTO it ("id", "value") VALUES (E'FR', E'Francia');
INSERT INTO it ("id", "value") VALUES (E'GA', E'Gabon');
INSERT INTO it ("id", "value") VALUES (E'GM', E'Gambia');
INSERT INTO it ("id", "value") VALUES (E'GE', E'Georgia');
INSERT INTO it ("id", "value") VALUES (E'GS', E'Georgia del Sud e Sandwich australi');
INSERT INTO it ("id", "value") VALUES (E'DE', E'Germania');
INSERT INTO it ("id", "value") VALUES (E'GH', E'Ghana');
INSERT INTO it ("id", "value") VALUES (E'JM', E'Giamaica');
INSERT INTO it ("id", "value") VALUES (E'JP', E'Giappone');
INSERT INTO it ("id", "value") VALUES (E'GI', E'Gibilterra');
INSERT INTO it ("id", "value") VALUES (E'DJ', E'Gibuti');
INSERT INTO it ("id", "value") VALUES (E'JO', E'Giordania');
INSERT INTO it ("id", "value") VALUES (E'GR', E'Grecia');
INSERT INTO it ("id", "value") VALUES (E'GD', E'Grenada');
INSERT INTO it ("id", "value") VALUES (E'GL', E'Groenlandia');
INSERT INTO it ("id", "value") VALUES (E'GP', E'Guadalupa');
INSERT INTO it ("id", "value") VALUES (E'GU', E'Guam');
INSERT INTO it ("id", "value") VALUES (E'GT', E'Guatemala');
INSERT INTO it ("id", "value") VALUES (E'GG', E'Guernsey');
INSERT INTO it ("id", "value") VALUES (E'GN', E'Guinea');
INSERT INTO it ("id", "value") VALUES (E'GQ', E'Guinea Equatoriale');
INSERT INTO it ("id", "value") VALUES (E'GW', E'Guinea-Bissau');
INSERT INTO it ("id", "value") VALUES (E'GY', E'Guyana');
INSERT INTO it ("id", "value") VALUES (E'GF', E'Guyana francese');
INSERT INTO it ("id", "value") VALUES (E'HT', E'Haiti');
INSERT INTO it ("id", "value") VALUES (E'HN', E'Honduras');
INSERT INTO it ("id", "value") VALUES (E'IN', E'India');
INSERT INTO it ("id", "value") VALUES (E'ID', E'Indonesia');
INSERT INTO it ("id", "value") VALUES (E'IR', E'Iran');
INSERT INTO it ("id", "value") VALUES (E'IQ', E'Iraq');
INSERT INTO it ("id", "value") VALUES (E'IE', E'Irlanda');
INSERT INTO it ("id", "value") VALUES (E'IS', E'Islanda');
INSERT INTO it ("id", "value") VALUES (E'AC', E'Isola Ascensione');
INSERT INTO it ("id", "value") VALUES (E'CX', E'Isola Christmas');
INSERT INTO it ("id", "value") VALUES (E'IM', E'Isola di Man');
INSERT INTO it ("id", "value") VALUES (E'NF', E'Isola Norfolk');
INSERT INTO it ("id", "value") VALUES (E'AX', E'Isole Åland');
INSERT INTO it ("id", "value") VALUES (E'IC', E'Isole Canarie');
INSERT INTO it ("id", "value") VALUES (E'KY', E'Isole Cayman');
INSERT INTO it ("id", "value") VALUES (E'CC', E'Isole Cocos (Keeling)');
INSERT INTO it ("id", "value") VALUES (E'CK', E'Isole Cook');
INSERT INTO it ("id", "value") VALUES (E'FO', E'Isole Fær Øer');
INSERT INTO it ("id", "value") VALUES (E'FK', E'Isole Falkland');
INSERT INTO it ("id", "value") VALUES (E'MP', E'Isole Marianne settentrionali');
INSERT INTO it ("id", "value") VALUES (E'MH', E'Isole Marshall');
INSERT INTO it ("id", "value") VALUES (E'PN', E'Isole Pitcairn');
INSERT INTO it ("id", "value") VALUES (E'SB', E'Isole Salomone');
INSERT INTO it ("id", "value") VALUES (E'TC', E'Isole Turks e Caicos');
INSERT INTO it ("id", "value") VALUES (E'VI', E'Isole Vergini Americane');
INSERT INTO it ("id", "value") VALUES (E'VG', E'Isole Vergini Britanniche');
INSERT INTO it ("id", "value") VALUES (E'IL', E'Israele');
INSERT INTO it ("id", "value") VALUES (E'IT', E'Italia');
INSERT INTO it ("id", "value") VALUES (E'JE', E'Jersey');
INSERT INTO it ("id", "value") VALUES (E'KZ', E'Kazakistan');
INSERT INTO it ("id", "value") VALUES (E'KE', E'Kenya');
INSERT INTO it ("id", "value") VALUES (E'KG', E'Kirghizistan');
INSERT INTO it ("id", "value") VALUES (E'KI', E'Kiribati');
INSERT INTO it ("id", "value") VALUES (E'XK', E'Kosovo');
INSERT INTO it ("id", "value") VALUES (E'KW', E'Kuwait');
INSERT INTO it ("id", "value") VALUES (E'LA', E'Laos');
INSERT INTO it ("id", "value") VALUES (E'LS', E'Lesotho');
INSERT INTO it ("id", "value") VALUES (E'LV', E'Lettonia');
INSERT INTO it ("id", "value") VALUES (E'LB', E'Libano');
INSERT INTO it ("id", "value") VALUES (E'LR', E'Liberia');
INSERT INTO it ("id", "value") VALUES (E'LY', E'Libia');
INSERT INTO it ("id", "value") VALUES (E'LI', E'Liechtenstein');
INSERT INTO it ("id", "value") VALUES (E'LT', E'Lituania');
INSERT INTO it ("id", "value") VALUES (E'LU', E'Lussemburgo');
INSERT INTO it ("id", "value") VALUES (E'MK', E'Macedonia del Nord');
INSERT INTO it ("id", "value") VALUES (E'MG', E'Madagascar');
INSERT INTO it ("id", "value") VALUES (E'MW', E'Malawi');
INSERT INTO it ("id", "value") VALUES (E'MY', E'Malaysia');
INSERT INTO it ("id", "value") VALUES (E'MV', E'Maldive');
INSERT INTO it ("id", "value") VALUES (E'ML', E'Mali');
INSERT INTO it ("id", "value") VALUES (E'MT', E'Malta');
INSERT INTO it ("id", "value") VALUES (E'MA', E'Marocco');
INSERT INTO it ("id", "value") VALUES (E'MQ', E'Martinica');
INSERT INTO it ("id", "value") VALUES (E'MR', E'Mauritania');
INSERT INTO it ("id", "value") VALUES (E'MU', E'Mauritius');
INSERT INTO it ("id", "value") VALUES (E'YT', E'Mayotte');
INSERT INTO it ("id", "value") VALUES (E'MX', E'Messico');
INSERT INTO it ("id", "value") VALUES (E'FM', E'Micronesia');
INSERT INTO it ("id", "value") VALUES (E'MD', E'Moldavia');
INSERT INTO it ("id", "value") VALUES (E'MC', E'Monaco');
INSERT INTO it ("id", "value") VALUES (E'MN', E'Mongolia');
INSERT INTO it ("id", "value") VALUES (E'ME', E'Montenegro');
INSERT INTO it ("id", "value") VALUES (E'MS', E'Montserrat');
INSERT INTO it ("id", "value") VALUES (E'MZ', E'Mozambico');
INSERT INTO it ("id", "value") VALUES (E'MM', E'Myanmar (Birmania)');
INSERT INTO it ("id", "value") VALUES (E'NA', E'Namibia');
INSERT INTO it ("id", "value") VALUES (E'NR', E'Nauru');
INSERT INTO it ("id", "value") VALUES (E'NP', E'Nepal');
INSERT INTO it ("id", "value") VALUES (E'NI', E'Nicaragua');
INSERT INTO it ("id", "value") VALUES (E'NE', E'Niger');
INSERT INTO it ("id", "value") VALUES (E'NG', E'Nigeria');
INSERT INTO it ("id", "value") VALUES (E'NU', E'Niue');
INSERT INTO it ("id", "value") VALUES (E'NO', E'Norvegia');
INSERT INTO it ("id", "value") VALUES (E'NC', E'Nuova Caledonia');
INSERT INTO it ("id", "value") VALUES (E'NZ', E'Nuova Zelanda');
INSERT INTO it ("id", "value") VALUES (E'OM', E'Oman');
INSERT INTO it ("id", "value") VALUES (E'NL', E'Paesi Bassi');
INSERT INTO it ("id", "value") VALUES (E'PK', E'Pakistan');
INSERT INTO it ("id", "value") VALUES (E'PW', E'Palau');
INSERT INTO it ("id", "value") VALUES (E'PA', E'Panamá');
INSERT INTO it ("id", "value") VALUES (E'PG', E'Papua Nuova Guinea');
INSERT INTO it ("id", "value") VALUES (E'PY', E'Paraguay');
INSERT INTO it ("id", "value") VALUES (E'PE', E'Perù');
INSERT INTO it ("id", "value") VALUES (E'PF', E'Polinesia francese');
INSERT INTO it ("id", "value") VALUES (E'PL', E'Polonia');
INSERT INTO it ("id", "value") VALUES (E'PT', E'Portogallo');
INSERT INTO it ("id", "value") VALUES (E'PR', E'Portorico');
INSERT INTO it ("id", "value") VALUES (E'XA', E'pseudo-accenti');
INSERT INTO it ("id", "value") VALUES (E'XB', E'pseudo-bidi');
INSERT INTO it ("id", "value") VALUES (E'QA', E'Qatar');
INSERT INTO it ("id", "value") VALUES (E'HK', E'RAS di Hong Kong');
INSERT INTO it ("id", "value") VALUES (E'MO', E'RAS di Macao');
INSERT INTO it ("id", "value") VALUES (E'GB', E'Regno Unito');
INSERT INTO it ("id", "value") VALUES (E'CF', E'Repubblica Centrafricana');
INSERT INTO it ("id", "value") VALUES (E'DO', E'Repubblica Dominicana');
INSERT INTO it ("id", "value") VALUES (E'RE', E'Riunione');
INSERT INTO it ("id", "value") VALUES (E'RO', E'Romania');
INSERT INTO it ("id", "value") VALUES (E'RW', E'Ruanda');
INSERT INTO it ("id", "value") VALUES (E'RU', E'Russia');
INSERT INTO it ("id", "value") VALUES (E'EH', E'Sahara occidentale');
INSERT INTO it ("id", "value") VALUES (E'KN', E'Saint Kitts e Nevis');
INSERT INTO it ("id", "value") VALUES (E'LC', E'Saint Lucia');
INSERT INTO it ("id", "value") VALUES (E'MF', E'Saint Martin');
INSERT INTO it ("id", "value") VALUES (E'VC', E'Saint Vincent e Grenadine');
INSERT INTO it ("id", "value") VALUES (E'BL', E'Saint-Barthélemy');
INSERT INTO it ("id", "value") VALUES (E'PM', E'Saint-Pierre e Miquelon');
INSERT INTO it ("id", "value") VALUES (E'WS', E'Samoa');
INSERT INTO it ("id", "value") VALUES (E'AS', E'Samoa americane');
INSERT INTO it ("id", "value") VALUES (E'SM', E'San Marino');
INSERT INTO it ("id", "value") VALUES (E'SH', E'Sant’Elena');
INSERT INTO it ("id", "value") VALUES (E'ST', E'São Tomé e Príncipe');
INSERT INTO it ("id", "value") VALUES (E'SN', E'Senegal');
INSERT INTO it ("id", "value") VALUES (E'RS', E'Serbia');
INSERT INTO it ("id", "value") VALUES (E'SC', E'Seychelles');
INSERT INTO it ("id", "value") VALUES (E'SL', E'Sierra Leone');
INSERT INTO it ("id", "value") VALUES (E'SG', E'Singapore');
INSERT INTO it ("id", "value") VALUES (E'SX', E'Sint Maarten');
INSERT INTO it ("id", "value") VALUES (E'SY', E'Siria');
INSERT INTO it ("id", "value") VALUES (E'SK', E'Slovacchia');
INSERT INTO it ("id", "value") VALUES (E'SI', E'Slovenia');
INSERT INTO it ("id", "value") VALUES (E'SO', E'Somalia');
INSERT INTO it ("id", "value") VALUES (E'ES', E'Spagna');
INSERT INTO it ("id", "value") VALUES (E'LK', E'Sri Lanka');
INSERT INTO it ("id", "value") VALUES (E'US', E'Stati Uniti');
INSERT INTO it ("id", "value") VALUES (E'SS', E'Sud Sudan');
INSERT INTO it ("id", "value") VALUES (E'ZA', E'Sudafrica');
INSERT INTO it ("id", "value") VALUES (E'SD', E'Sudan');
INSERT INTO it ("id", "value") VALUES (E'SR', E'Suriname');
INSERT INTO it ("id", "value") VALUES (E'SJ', E'Svalbard e Jan Mayen');
INSERT INTO it ("id", "value") VALUES (E'SE', E'Svezia');
INSERT INTO it ("id", "value") VALUES (E'CH', E'Svizzera');
INSERT INTO it ("id", "value") VALUES (E'SZ', E'Swaziland');
INSERT INTO it ("id", "value") VALUES (E'TJ', E'Tagikistan');
INSERT INTO it ("id", "value") VALUES (E'TW', E'Taiwan');
INSERT INTO it ("id", "value") VALUES (E'TZ', E'Tanzania');
INSERT INTO it ("id", "value") VALUES (E'TF', E'Terre australi francesi');
INSERT INTO it ("id", "value") VALUES (E'PS', E'Territori palestinesi');
INSERT INTO it ("id", "value") VALUES (E'IO', E'Territorio britannico dell’Oceano Indiano');
INSERT INTO it ("id", "value") VALUES (E'TH', E'Thailandia');
INSERT INTO it ("id", "value") VALUES (E'TL', E'Timor Est');
INSERT INTO it ("id", "value") VALUES (E'TG', E'Togo');
INSERT INTO it ("id", "value") VALUES (E'TK', E'Tokelau');
INSERT INTO it ("id", "value") VALUES (E'TO', E'Tonga');
INSERT INTO it ("id", "value") VALUES (E'TT', E'Trinidad e Tobago');
INSERT INTO it ("id", "value") VALUES (E'TA', E'Tristan da Cunha');
INSERT INTO it ("id", "value") VALUES (E'TN', E'Tunisia');
INSERT INTO it ("id", "value") VALUES (E'TR', E'Turchia');
INSERT INTO it ("id", "value") VALUES (E'TM', E'Turkmenistan');
INSERT INTO it ("id", "value") VALUES (E'TV', E'Tuvalu');
INSERT INTO it ("id", "value") VALUES (E'UA', E'Ucraina');
INSERT INTO it ("id", "value") VALUES (E'UG', E'Uganda');
INSERT INTO it ("id", "value") VALUES (E'HU', E'Ungheria');
INSERT INTO it ("id", "value") VALUES (E'UY', E'Uruguay');
INSERT INTO it ("id", "value") VALUES (E'UZ', E'Uzbekistan');
INSERT INTO it ("id", "value") VALUES (E'VU', E'Vanuatu');
INSERT INTO it ("id", "value") VALUES (E'VE', E'Venezuela');
INSERT INTO it ("id", "value") VALUES (E'VN', E'Vietnam');
INSERT INTO it ("id", "value") VALUES (E'WF', E'Wallis e Futuna');
INSERT INTO it ("id", "value") VALUES (E'YE', E'Yemen');
INSERT INTO it ("id", "value") VALUES (E'ZM', E'Zambia');
INSERT INTO it ("id", "value") VALUES (E'ZW', E'Zimbabwe');
